import { SlashCommandBuilder } from 'discord.js';
import { createEmbed } from '../../utils/embeds.js';
import { InteractionHelper } from '../../utils/interactionHelper.js';

const VERSES = [
  // Genesis
  { ref: "Genesis 1:1", text: "In the beginning God created the heavens and the earth." },
  { ref: "Genesis 1:2", text: "Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters." },
  { ref: "Genesis 1:3", text: "And God said, 'Let there be light,' and there was light." },
  { ref: "Genesis 1:26", text: "Then God said, 'Let us make mankind in our image, in our likeness, so that they may rule over the fish in the sea and the birds in the sky.'" },
  { ref: "Genesis 1:27", text: "So God created mankind in his own image, in the image of God he created them; male and female he created them." },
  { ref: "Genesis 1:31", text: "God saw all that he had made, and it was very good." },
  { ref: "Genesis 2:7", text: "Then the Lord God formed a man from the dust of the ground and breathed into his nostrils the breath of life, and the man became a living being." },
  { ref: "Genesis 2:18", text: "The Lord God said, 'It is not good for the man to be alone. I will make a helper suitable for him.'" },
  { ref: "Genesis 2:24", text: "That is why a man leaves his father and mother and is united to his wife, and they become one flesh." },
  { ref: "Genesis 3:15", text: "And I will put enmity between you and the woman, and between your offspring and hers; he will crush your head, and you will strike his heel." },
  { ref: "Genesis 6:8", text: "But Noah found favor in the eyes of the Lord." },
  { ref: "Genesis 8:1", text: "But God remembered Noah and all the wild animals and the livestock that were with him in the ark, and he sent a wind over the earth, and the waters receded." },
  { ref: "Genesis 9:13", text: "I have set my rainbow in the clouds, and it will be the sign of the covenant between me and the earth." },
  { ref: "Genesis 12:1", text: "The Lord had said to Abram, 'Go from your country, your people and your father's household to the land I will show you.'" },
  { ref: "Genesis 12:2", text: "I will make you into a great nation, and I will bless you; I will make your name great, and you will be a blessing." },
  { ref: "Genesis 15:1", text: "After this, the word of the Lord came to Abram in a vision: 'Do not be afraid, Abram. I am your shield, your very great reward.'" },
  { ref: "Genesis 15:6", text: "Abram believed the Lord, and he credited it to him as righteousness." },
  { ref: "Genesis 18:14", text: "Is anything too hard for the Lord?" },
  { ref: "Genesis 21:1", text: "Now the Lord was gracious to Sarah as he had said, and the Lord did for Sarah what he had promised." },
  { ref: "Genesis 22:14", text: "So Abraham called that place The Lord Will Provide. And to this day it is said, 'On the mountain of the Lord it will be provided.'" },
  { ref: "Genesis 28:15", text: "I am with you and will watch over you wherever you go, and I will bring you back to this land. I will not leave you until I have done what I have promised you." },
  { ref: "Genesis 50:20", text: "You intended to harm me, but God intended it for good to accomplish what is now being done, the saving of many lives." },
  // Exodus
  { ref: "Exodus 3:14", text: "God said to Moses, 'I AM WHO I AM. This is what you are to say to the Israelites: I AM has sent me to you.'" },
  { ref: "Exodus 14:14", text: "The Lord will fight for you; you need only to be still." },
  { ref: "Exodus 15:2", text: "The Lord is my strength and my defense; he has become my salvation. He is my God, and I will praise him, my father's God, and I will exalt him." },
  { ref: "Exodus 20:2", text: "I am the Lord your God, who brought you out of Egypt, out of the land of slavery." },
  { ref: "Exodus 20:3", text: "You shall have no other gods before me." },
  { ref: "Exodus 20:12", text: "Honor your father and your mother, so that you may live long in the land the Lord your God is giving you." },
  { ref: "Exodus 20:13", text: "You shall not murder." },
  { ref: "Exodus 20:15", text: "You shall not steal." },
  { ref: "Exodus 33:14", text: "The Lord replied, 'My Presence will go with you, and I will give you rest.'" },
  { ref: "Exodus 34:6", text: "And he passed in front of Moses, proclaiming, 'The Lord, the Lord, the compassionate and gracious God, slow to anger, abounding in love and faithfulness.'" },
  // Leviticus
  { ref: "Leviticus 19:18", text: "Do not seek revenge or bear a grudge against anyone among your people, but love your neighbor as yourself. I am the Lord." },
  { ref: "Leviticus 20:26", text: "You are to be holy to me because I, the Lord, am holy, and I have set you apart from the nations to be my own." },
  // Numbers
  { ref: "Numbers 6:24", text: "The Lord bless you and keep you;" },
  { ref: "Numbers 6:25", text: "the Lord make his face shine on you and be gracious to you;" },
  { ref: "Numbers 6:26", text: "the Lord turn his face toward you and give you peace." },
  { ref: "Numbers 14:18", text: "The Lord is slow to anger, abounding in love and forgiving sin and rebellion." },
  // Deuteronomy
  { ref: "Deuteronomy 4:29", text: "But if from there you seek the Lord your God, you will find him if you seek him with all your heart and with all your soul." },
  { ref: "Deuteronomy 6:4", text: "Hear, O Israel: The Lord our God, the Lord is one." },
  { ref: "Deuteronomy 6:5", text: "Love the Lord your God with all your heart and with all your soul and with all your strength." },
  { ref: "Deuteronomy 7:9", text: "Know therefore that the Lord your God is God; he is the faithful God, keeping his covenant of love to a thousand generations of those who love him and keep his commandments." },
  { ref: "Deuteronomy 8:3", text: "Man does not live on bread alone but on every word that comes from the mouth of the Lord." },
  { ref: "Deuteronomy 10:12", text: "And now, Israel, what does the Lord your God ask of you but to fear the Lord your God, to walk in obedience to him, to love him, to serve the Lord your God with all your heart and with all your soul." },
  { ref: "Deuteronomy 11:1", text: "Love the Lord your God and keep his requirements, his decrees, his laws and his commands always." },
  { ref: "Deuteronomy 28:2", text: "All these blessings will come on you and accompany you if you obey the Lord your God." },
  { ref: "Deuteronomy 29:29", text: "The secret things belong to the Lord our God, but the things revealed belong to us and to our children forever, that we may follow all the words of this law." },
  { ref: "Deuteronomy 30:19", text: "I have set before you life and death, blessings and curses. Now choose life, so that you and your children may live." },
  { ref: "Deuteronomy 31:6", text: "Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you; he will never leave you nor forsake you." },
  { ref: "Deuteronomy 31:8", text: "The Lord himself goes before you and will be with you; he will never leave you nor forsake you. Do not be afraid; do not be discouraged." },
  { ref: "Deuteronomy 33:27", text: "The eternal God is your refuge, and underneath are the everlasting arms." },
  // Joshua
  { ref: "Joshua 1:7", text: "Be strong and very courageous. Be careful to obey all the law my servant Moses gave you; do not turn from it to the right or to the left, that you may be successful wherever you go." },
  { ref: "Joshua 1:8", text: "Keep this Book of the Law always on your lips; meditate on it day and night, so that you may be careful to do everything written in it. Then you will be prosperous and successful." },
  { ref: "Joshua 1:9", text: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go." },
  { ref: "Joshua 24:15", text: "But as for me and my household, we will serve the Lord." },
  // Judges
  { ref: "Judges 6:16", text: "The Lord answered, 'I will be with you, and you will strike down all the Midianites, leaving none alive.'" },
  // Ruth
  { ref: "Ruth 1:16", text: "But Ruth replied, 'Don't urge me to leave you or to turn back from you. Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God.'" },
  { ref: "Ruth 2:12", text: "May the Lord repay you for what you have done. May you be richly rewarded by the Lord, the God of Israel, under whose wings you have come to take refuge." },
  // 1 Samuel
  { ref: "1 Samuel 2:2", text: "There is no one holy like the Lord; there is no one besides you; there is no Rock like our God." },
  { ref: "1 Samuel 16:7", text: "The Lord does not look at the things people look at. People look at the outward appearance, but the Lord looks at the heart." },
  // 2 Samuel
  { ref: "2 Samuel 22:2", text: "He said: 'The Lord is my rock, my fortress and my deliverer.'" },
  { ref: "2 Samuel 22:31", text: "As for God, his way is perfect: The Lord's word is flawless; he shields all who take refuge in him." },
  // 1 Kings
  { ref: "1 Kings 8:56", text: "Praise be to the Lord, who has given rest to his people Israel just as he promised. Not one word has failed of all the good promises he gave through his servant Moses." },
  // 1 Chronicles
  { ref: "1 Chronicles 16:34", text: "Give thanks to the Lord, for he is good; his love endures forever." },
  { ref: "1 Chronicles 28:20", text: "Be strong and courageous, and do the work. Do not be afraid or discouraged, for the Lord God, my God, is with you. He will not fail you or forsake you." },
  // 2 Chronicles
  { ref: "2 Chronicles 7:14", text: "If my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven, and I will forgive their sin and will heal their land." },
  { ref: "2 Chronicles 15:7", text: "But as for you, be strong and do not give up, for your work will be rewarded." },
  { ref: "2 Chronicles 20:15", text: "He said: 'Listen, King Jehoshaphat and all who live in Judah and Jerusalem! This is what the Lord says to you: Do not be afraid or discouraged because of this vast army. For the battle is not yours, but God's.'" },
  // Ezra
  { ref: "Ezra 8:22", text: "The gracious hand of our God is on everyone who looks to him, but his great anger is against all who forsake him." },
  // Nehemiah
  { ref: "Nehemiah 8:10", text: "The joy of the Lord is your strength." },
  // Job
  { ref: "Job 1:21", text: "Naked I came from my mother's womb, and naked I will depart. The Lord gave and the Lord has taken away; may the name of the Lord be praised." },
  { ref: "Job 19:25", text: "I know that my redeemer lives, and that in the end he will stand on the earth." },
  { ref: "Job 23:10", text: "But he knows the way that I take; when he has tested me, I will come forth as gold." },
  { ref: "Job 37:14", text: "Listen to this, Job; stop and consider God's wonders." },
  { ref: "Job 42:2", text: "I know that you can do all things; no purpose of yours can be thwarted." },
  // Psalms
  { ref: "Psalm 1:1", text: "Blessed is the one who does not walk in step with the wicked or stand in the way that sinners take or sit in the company of mockers." },
  { ref: "Psalm 1:2", text: "But whose delight is in the law of the Lord, and who meditates on his law day and night." },
  { ref: "Psalm 1:3", text: "That person is like a tree planted by streams of water, which yields its fruit in season and whose leaf does not wither—whatever they do prospers." },
  { ref: "Psalm 3:3", text: "But you, Lord, are a shield around me, my glory, the One who lifts my head high." },
  { ref: "Psalm 4:8", text: "In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety." },
  { ref: "Psalm 5:3", text: "In the morning, Lord, you hear my voice; in the morning I lay my requests before you and wait expectantly." },
  { ref: "Psalm 9:1", text: "I will give thanks to you, Lord, with all my heart; I will tell of all your wonderful deeds." },
  { ref: "Psalm 9:9", text: "The Lord is a refuge for the oppressed, a stronghold in times of trouble." },
  { ref: "Psalm 9:10", text: "Those who know your name trust in you, for you, Lord, have never forsaken those who seek you." },
  { ref: "Psalm 16:8", text: "I keep my eyes always on the Lord. With him at my right hand, I will not be shaken." },
  { ref: "Psalm 16:11", text: "You make known to me the path of life; you will fill me with joy in your presence, with eternal pleasures at your right hand." },
  { ref: "Psalm 18:2", text: "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge, my shield and the horn of my salvation, my stronghold." },
  { ref: "Psalm 19:1", text: "The heavens declare the glory of God; the skies proclaim the work of his hands." },
  { ref: "Psalm 19:7", text: "The law of the Lord is perfect, refreshing the soul. The statutes of the Lord are trustworthy, making wise the simple." },
  { ref: "Psalm 19:14", text: "May these words of my mouth and this meditation of my heart be pleasing in your sight, Lord, my Rock and my Redeemer." },
  { ref: "Psalm 22:24", text: "For he has not despised or scorned the suffering of the afflicted one; he has not hidden his face from him but has listened to his cry for help." },
  { ref: "Psalm 23:1", text: "The Lord is my shepherd, I lack nothing." },
  { ref: "Psalm 23:2", text: "He makes me lie down in green pastures, he leads me beside quiet waters," },
  { ref: "Psalm 23:3", text: "he refreshes my soul. He guides me along the right paths for his name's sake." },
  { ref: "Psalm 23:4", text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me." },
  { ref: "Psalm 23:5", text: "You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows." },
  { ref: "Psalm 23:6", text: "Surely your goodness and love will follow me all the days of my life, and I will dwell in the house of the Lord forever." },
  { ref: "Psalm 25:4", text: "Show me your ways, Lord, teach me your paths." },
  { ref: "Psalm 25:5", text: "Guide me in your truth and teach me, for you are God my Savior, and my hope is in you all day long." },
  { ref: "Psalm 27:1", text: "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid?" },
  { ref: "Psalm 27:4", text: "One thing I ask from the Lord, this only do I seek: that I may dwell in the house of the Lord all the days of my life." },
  { ref: "Psalm 27:14", text: "Wait for the Lord; be strong and take heart and wait for the Lord." },
  { ref: "Psalm 28:7", text: "The Lord is my strength and my shield; my heart trusts in him, and he helps me. My heart leaps for joy, and with my song I praise him." },
  { ref: "Psalm 30:2", text: "Lord my God, I called to you for help, and you healed me." },
  { ref: "Psalm 30:5", text: "For his anger lasts only a moment, but his favor lasts a lifetime; weeping may stay for the night, but rejoicing comes in the morning." },
  { ref: "Psalm 31:3", text: "Since you are my rock and my fortress, for the sake of your name lead and guide me." },
  { ref: "Psalm 31:24", text: "Be strong and take heart, all you who hope in the Lord." },
  { ref: "Psalm 32:7", text: "You are my hiding place; you will protect me from trouble and surround me with songs of deliverance." },
  { ref: "Psalm 32:8", text: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you." },
  { ref: "Psalm 33:4", text: "For the word of the Lord is right and true; he is faithful in all he does." },
  { ref: "Psalm 33:18", text: "But the eyes of the Lord are on those who fear him, on those whose hope is in his unfailing love." },
  { ref: "Psalm 34:4", text: "I sought the Lord, and he answered me; he delivered me from all my fears." },
  { ref: "Psalm 34:7", text: "The angel of the Lord encamps around those who fear him, and he delivers them." },
  { ref: "Psalm 34:8", text: "Taste and see that the Lord is good; blessed is the one who takes refuge in him." },
  { ref: "Psalm 34:18", text: "The Lord is close to the brokenhearted and saves those who are crushed in spirit." },
  { ref: "Psalm 34:19", text: "The righteous person may have many troubles, but the Lord delivers him from them all." },
  { ref: "Psalm 36:7", text: "How priceless is your unfailing love, O God! People take refuge in the shadow of your wings." },
  { ref: "Psalm 37:3", text: "Trust in the Lord and do good; dwell in the land and enjoy safe pasture." },
  { ref: "Psalm 37:4", text: "Take delight in the Lord, and he will give you the desires of your heart." },
  { ref: "Psalm 37:5", text: "Commit your way to the Lord; trust in him and he will do this:" },
  { ref: "Psalm 37:7", text: "Be still before the Lord and wait patiently for him." },
  { ref: "Psalm 37:23", text: "The Lord makes firm the steps of the one who delights in him." },
  { ref: "Psalm 37:25", text: "I was young and now I am old, yet I have never seen the righteous forsaken or their children begging bread." },
  { ref: "Psalm 40:1", text: "I waited patiently for the Lord; he turned to me and heard my cry." },
  { ref: "Psalm 40:3", text: "He put a new song in my mouth, a hymn of praise to our God." },
  { ref: "Psalm 40:17", text: "But as for me, I am poor and needy; may the Lord think of me. You are my help and my deliverer; you are my God, do not delay." },
  { ref: "Psalm 42:1", text: "As the deer pants for streams of water, so my soul pants for you, my God." },
  { ref: "Psalm 42:5", text: "Why, my soul, are you downcast? Why so disturbed within me? Put your hope in God, for I will yet praise him, my Savior and my God." },
  { ref: "Psalm 43:5", text: "Why, my soul, are you downcast? Why so disturbed within me? Put your hope in God, for I will yet praise him, my Savior and my God." },
  { ref: "Psalm 46:1", text: "God is our refuge and strength, an ever-present help in trouble." },
  { ref: "Psalm 46:10", text: "He says, 'Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.'" },
  { ref: "Psalm 47:1", text: "Clap your hands, all you nations; shout to God with cries of joy." },
  { ref: "Psalm 48:14", text: "For this God is our God for ever and ever; he will be our guide even to the end." },
  { ref: "Psalm 51:1", text: "Have mercy on me, O God, according to your unfailing love; according to your great compassion blot out my transgressions." },
  { ref: "Psalm 51:10", text: "Create in me a pure heart, O God, and renew a steadfast spirit within me." },
  { ref: "Psalm 51:17", text: "My sacrifice, O God, is a broken spirit; a broken and contrite heart you, God, will not despise." },
  { ref: "Psalm 55:22", text: "Cast your cares on the Lord and he will sustain you; he will never let the righteous be shaken." },
  { ref: "Psalm 56:3", text: "When I am afraid, I put my trust in you." },
  { ref: "Psalm 62:5", text: "Yes, my soul, find rest in God; my hope comes from him." },
  { ref: "Psalm 62:8", text: "Trust in him at all times, you people; pour out your hearts to him, for God is our refuge." },
  { ref: "Psalm 63:1", text: "You, God, are my God, earnestly I seek you; I thirst for you, my whole being longs for you, in a dry and parched land where there is no water." },
  { ref: "Psalm 68:5", text: "A father to the fatherless, a defender of widows, is God in his holy dwelling." },
  { ref: "Psalm 71:5", text: "For you have been my hope, Sovereign Lord, my confidence since my youth." },
  { ref: "Psalm 73:26", text: "My flesh and my heart may fail, but God is the strength of my heart and my portion forever." },
  { ref: "Psalm 84:11", text: "For the Lord God is a sun and shield; the Lord bestows favor and honor; no good thing does he withhold from those whose walk is blameless." },
  { ref: "Psalm 86:5", text: "You, Lord, are forgiving and good, abounding in love to all who call to you." },
  { ref: "Psalm 86:15", text: "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love and faithfulness." },
  { ref: "Psalm 90:1", text: "Lord, you have been our dwelling place throughout all generations." },
  { ref: "Psalm 90:2", text: "Before the mountains were born or you brought forth the whole world, from everlasting to everlasting you are God." },
  { ref: "Psalm 91:1", text: "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty." },
  { ref: "Psalm 91:2", text: "I will say of the Lord, 'He is my refuge and my fortress, my God, in whom I trust.'" },
  { ref: "Psalm 91:4", text: "He will cover you with his feathers, and under his wings you will find refuge; his faithfulness will be your shield and rampart." },
  { ref: "Psalm 91:11", text: "For he will command his angels concerning you to guard you in all your ways." },
  { ref: "Psalm 94:19", text: "When anxiety was great within me, your consolation brought me joy." },
  { ref: "Psalm 100:1", text: "Shout for joy to the Lord, all the earth." },
  { ref: "Psalm 100:3", text: "Know that the Lord is God. It is he who made us, and we are his; we are his people, the sheep of his pasture." },
  { ref: "Psalm 100:4", text: "Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name." },
  { ref: "Psalm 100:5", text: "For the Lord is good and his love endures forever; his faithfulness continues through all generations." },
  { ref: "Psalm 103:1", text: "Praise the Lord, my soul; all my inmost being, praise his holy name." },
  { ref: "Psalm 103:2", text: "Praise the Lord, my soul, and forget not all his benefits—" },
  { ref: "Psalm 103:3", text: "who forgives all your sins and heals all your diseases," },
  { ref: "Psalm 103:4", text: "who redeems your life from the pit and crowns you with love and compassion," },
  { ref: "Psalm 103:8", text: "The Lord is compassionate and gracious, slow to anger, abounding in love." },
  { ref: "Psalm 103:11", text: "For as high as the heavens are above the earth, so great is his love for those who fear him." },
  { ref: "Psalm 103:12", text: "as far as the east is from the west, so far has he removed our transgressions from us." },
  { ref: "Psalm 103:13", text: "As a father has compassion on his children, so the Lord has compassion on those who fear him." },
  { ref: "Psalm 107:1", text: "Give thanks to the Lord, for he is good; his love endures forever." },
  { ref: "Psalm 107:9", text: "for he satisfies the thirsty and fills the hungry with good things." },
  { ref: "Psalm 112:7", text: "They will have no fear of bad news; their hearts are steadfast, trusting in the Lord." },
  { ref: "Psalm 118:6", text: "The Lord is with me; I will not be afraid. What can mere mortals do to me?" },
  { ref: "Psalm 118:7", text: "The Lord is with me; he is my helper." },
  { ref: "Psalm 118:14", text: "The Lord is my strength and my defense; he has become my salvation." },
  { ref: "Psalm 118:24", text: "The Lord has done it this very day; let us rejoice today and be glad." },
  { ref: "Psalm 119:9", text: "How can a young person stay on the path of purity? By living according to your word." },
  { ref: "Psalm 119:11", text: "I have hidden your word in my heart that I might not sin against you." },
  { ref: "Psalm 119:18", text: "Open my eyes that I may see wonderful things in your law." },
  { ref: "Psalm 119:30", text: "I have chosen the way of faithfulness; I have set my heart on your laws." },
  { ref: "Psalm 119:50", text: "My comfort in my suffering is this: Your promise preserves my life." },
  { ref: "Psalm 119:65", text: "Do good to your servant according to your word, Lord." },
  { ref: "Psalm 119:105", text: "Your word is a lamp for my feet, a light on my path." },
  { ref: "Psalm 119:114", text: "You are my refuge and my shield; I have put my hope in your word." },
  { ref: "Psalm 119:130", text: "The unfolding of your words gives light; it gives understanding to the simple." },
  { ref: "Psalm 119:160", text: "All your words are true; all your righteous laws are eternal." },
  { ref: "Psalm 121:1", text: "I lift up my eyes to the mountains—where does my help come from?" },
  { ref: "Psalm 121:2", text: "My help comes from the Lord, the Maker of heaven and earth." },
  { ref: "Psalm 121:3", text: "He will not let your foot slip—he who watches over you will not slumber." },
  { ref: "Psalm 121:5", text: "The Lord watches over you—the Lord is your shade at your right hand." },
  { ref: "Psalm 121:8", text: "the Lord will watch over your coming and going both now and forevermore." },
  { ref: "Psalm 127:1", text: "Unless the Lord builds the house, the builders labor in vain. Unless the Lord watches over the city, the guards stand watch in vain." },
  { ref: "Psalm 128:1", text: "Blessed are all who fear the Lord, who walk in obedience to him." },
  { ref: "Psalm 130:7", text: "Israel, put your hope in the Lord, for with the Lord is unfailing love and with him is full redemption." },
  { ref: "Psalm 136:1", text: "Give thanks to the Lord, for he is good. His love endures forever." },
  { ref: "Psalm 138:3", text: "When I called, you answered me; you greatly emboldened me." },
  { ref: "Psalm 139:1", text: "You have searched me, Lord, and you know me." },
  { ref: "Psalm 139:2", text: "You know when I sit and when I rise; you perceive my thoughts from afar." },
  { ref: "Psalm 139:7", text: "Where can I go from your Spirit? Where can I flee from your presence?" },
  { ref: "Psalm 139:13", text: "For you created my inmost being; you knit me together in my mother's womb." },
  { ref: "Psalm 139:14", text: "I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well." },
  { ref: "Psalm 139:16", text: "Your eyes saw my unformed body; all the days ordained for me were written in your book before one of them came to be." },
  { ref: "Psalm 139:23", text: "Search me, God, and know my heart; test me and know my anxious thoughts." },
  { ref: "Psalm 139:24", text: "See if there is any offensive way in me, and lead me in the way everlasting." },
  { ref: "Psalm 143:8", text: "Let the morning bring me word of your unfailing love, for I have put my trust in you. Show me the way I should go, for to you I entrust my life." },
  { ref: "Psalm 143:10", text: "Teach me to do your will, for you are my God; may your good Spirit lead me on level ground." },
  { ref: "Psalm 145:3", text: "Great is the Lord and most worthy of praise; his greatness no one can fathom." },
  { ref: "Psalm 145:8", text: "The Lord is gracious and compassionate, slow to anger and rich in love." },
  { ref: "Psalm 145:9", text: "The Lord is good to all; he has compassion on all he has made." },
  { ref: "Psalm 145:18", text: "The Lord is near to all who call on him, to all who call on him in truth." },
  { ref: "Psalm 145:19", text: "He fulfills the desires of those who fear him; he hears their cry and saves them." },
  { ref: "Psalm 147:3", text: "He heals the brokenhearted and binds up their wounds." },
  { ref: "Psalm 150:6", text: "Let everything that has breath praise the Lord. Praise the Lord." },
  // Proverbs
  { ref: "Proverbs 1:7", text: "The fear of the Lord is the beginning of knowledge, but fools despise wisdom and instruction." },
  { ref: "Proverbs 2:6", text: "For the Lord gives wisdom; from his mouth come knowledge and understanding." },
  { ref: "Proverbs 3:1", text: "My son, do not forget my teaching, but keep my commands in your heart." },
  { ref: "Proverbs 3:3", text: "Let love and faithfulness never leave you; bind them around your neck, write them on the tablet of your heart." },
  { ref: "Proverbs 3:5", text: "Trust in the Lord with all your heart and lean not on your own understanding;" },
  { ref: "Proverbs 3:6", text: "in all your ways submit to him, and he will make your paths straight." },
  { ref: "Proverbs 3:7", text: "Do not be wise in your own eyes; fear the Lord and shun evil." },
  { ref: "Proverbs 4:7", text: "The beginning of wisdom is this: Get wisdom. Though it cost all you have, get understanding." },
  { ref: "Proverbs 4:23", text: "Above all else, guard your heart, for everything you do flows from it." },
  { ref: "Proverbs 6:6", text: "Go to the ant, you sluggard; consider its ways and be wise!" },
  { ref: "Proverbs 8:11", text: "For wisdom is more precious than rubies, and nothing you desire can compare with her." },
  { ref: "Proverbs 9:10", text: "The fear of the Lord is the beginning of wisdom, and knowledge of the Holy One is understanding." },
  { ref: "Proverbs 10:12", text: "Hatred stirs up conflict, but love covers over all wrongs." },
  { ref: "Proverbs 11:2", text: "When pride comes, then comes disgrace, but with humility comes wisdom." },
  { ref: "Proverbs 11:14", text: "For lack of guidance a nation falls, but victory is won through many advisers." },
  { ref: "Proverbs 11:24", text: "One person gives freely, yet gains even more; another withholds unduly, but comes to poverty." },
  { ref: "Proverbs 11:25", text: "A generous person will prosper; whoever refreshes others will be refreshed." },
  { ref: "Proverbs 12:15", text: "The way of fools seems right to them, but the wise listen to advice." },
  { ref: "Proverbs 13:20", text: "Walk with the wise and become wise, for a companion of fools suffers harm." },
  { ref: "Proverbs 14:12", text: "There is a way that appears to be right, but in the end it leads to death." },
  { ref: "Proverbs 14:29", text: "Whoever is patient has great understanding, but one who is quick-tempered displays folly." },
  { ref: "Proverbs 15:1", text: "A gentle answer turns away wrath, but a harsh word stirs up anger." },
  { ref: "Proverbs 15:3", text: "The eyes of the Lord are everywhere, keeping watch on the wicked and the good." },
  { ref: "Proverbs 15:13", text: "A happy heart makes the face cheerful, but heartache crushes the spirit." },
  { ref: "Proverbs 16:3", text: "Commit to the Lord whatever you do, and he will establish your plans." },
  { ref: "Proverbs 16:9", text: "In their hearts humans plan their course, but the Lord establishes their steps." },
  { ref: "Proverbs 16:18", text: "Pride goes before destruction, a haughty spirit before a fall." },
  { ref: "Proverbs 17:9", text: "Whoever would foster love covers over an offense, but whoever repeats the matter separates close friends." },
  { ref: "Proverbs 17:17", text: "A friend loves at all times, and a brother is born for a time of adversity." },
  { ref: "Proverbs 17:22", text: "A cheerful heart is good medicine, but a crushed spirit dries up the bones." },
  { ref: "Proverbs 18:10", text: "The name of the Lord is a fortified tower; the righteous run to it and are safe." },
  { ref: "Proverbs 18:24", text: "One who has unreliable friends soon comes to ruin, but there is a friend who sticks closer than a brother." },
  { ref: "Proverbs 19:11", text: "A person's wisdom yields patience; it is to one's glory to overlook an offense." },
  { ref: "Proverbs 19:21", text: "Many are the plans in a person's heart, but it is the Lord's purpose that prevails." },
  { ref: "Proverbs 20:7", text: "The righteous lead blameless lives; blessed are their children after them." },
  { ref: "Proverbs 21:2", text: "A person may think their own ways are right, but the Lord weighs the heart." },
  { ref: "Proverbs 21:21", text: "Whoever pursues righteousness and love finds life, prosperity and honor." },
  { ref: "Proverbs 22:6", text: "Start children off on the way they should go, and even when they are old they will not turn from it." },
  { ref: "Proverbs 22:9", text: "The generous will themselves be blessed, for they share their food with the poor." },
  { ref: "Proverbs 23:7", text: "For as he thinks in his heart, so is he." },
  { ref: "Proverbs 24:10", text: "If you falter in a time of trouble, how small is your strength!" },
  { ref: "Proverbs 24:16", text: "For though the righteous fall seven times, they rise again, but the wicked stumble when calamity strikes." },
  { ref: "Proverbs 25:11", text: "Like apples of gold in settings of silver is a ruling rightly given." },
  { ref: "Proverbs 27:1", text: "Do not boast about tomorrow, for you do not know what a day may bring." },
  { ref: "Proverbs 27:17", text: "As iron sharpens iron, so one person sharpens another." },
  { ref: "Proverbs 28:1", text: "The wicked flee though no one pursues, but the righteous are as bold as a lion." },
  { ref: "Proverbs 29:25", text: "Fear of man will prove to be a snare, but whoever trusts in the Lord is kept safe." },
  { ref: "Proverbs 31:25", text: "She is clothed with strength and dignity; she can laugh at the days to come." },
  { ref: "Proverbs 31:30", text: "Charm is deceptive, and beauty is fleeting; but a woman who fears the Lord is to be praised." },
  // Ecclesiastes
  { ref: "Ecclesiastes 3:1", text: "There is a time for everything, and a season for every activity under the heavens." },
  { ref: "Ecclesiastes 3:11", text: "He has made everything beautiful in its time. He has also set eternity in the human heart." },
  { ref: "Ecclesiastes 4:9", text: "Two are better than one, because they have a good return for their labor." },
  { ref: "Ecclesiastes 4:12", text: "Though one may be overpowered, two can defend themselves. A cord of three strands is not quickly broken." },
  { ref: "Ecclesiastes 5:2", text: "Do not be quick with your mouth, do not be hasty in your heart to utter anything before God. God is in heaven and you are on earth, so let your words be few." },
  { ref: "Ecclesiastes 9:11", text: "The race is not to the swift or the battle to the strong, nor does food come to the wise or wealth to the brilliant or favor to the learned; but time and chance happen to them all." },
  { ref: "Ecclesiastes 12:13", text: "Fear God and keep his commandments, for this is the duty of all mankind." },
  // Song of Solomon
  { ref: "Song of Solomon 8:7", text: "Many waters cannot quench love; rivers cannot sweep it away." },
  // Isaiah
  { ref: "Isaiah 1:18", text: "Come now, let us settle the matter, says the Lord. Though your sins are like scarlet, they shall be as white as snow." },
  { ref: "Isaiah 6:8", text: "Then I heard the voice of the Lord saying, 'Whom shall I send? And who will go for us?' And I said, 'Here am I. Send me!'" },
  { ref: "Isaiah 7:14", text: "Therefore the Lord himself will give you a sign: The virgin will conceive and give birth to a son, and will call him Immanuel." },
  { ref: "Isaiah 9:6", text: "For to us a child is born, to us a son is given, and the government will be on his shoulders. And he will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace." },
  { ref: "Isaiah 12:2", text: "Surely God is my salvation; I will trust and not be afraid. The Lord, the Lord himself, is my strength and my defense; he has become my salvation." },
  { ref: "Isaiah 25:1", text: "Lord, you are my God; I will exalt you and praise your name, for in perfect faithfulness you have done wonderful things, things planned long ago." },
  { ref: "Isaiah 26:3", text: "You will keep in perfect peace those whose minds are steadfast, because they trust in you." },
  { ref: "Isaiah 26:4", text: "Trust in the Lord forever, for the Lord, the Lord himself, is the Rock eternal." },
  { ref: "Isaiah 28:29", text: "All this also comes from the Lord Almighty, whose plan is wonderful, whose wisdom is magnificent." },
  { ref: "Isaiah 30:18", text: "Yet the Lord longs to be gracious to you; therefore he will rise up to show you compassion. For the Lord is a God of justice. Blessed are all who wait for him!" },
  { ref: "Isaiah 30:21", text: "Whether you turn to the right or to the left, your ears will hear a voice behind you, saying, 'This is the way; walk in it.'" },
  { ref: "Isaiah 33:2", text: "Lord, be gracious to us; we long for you. Be our strength every morning, our salvation in time of distress." },
  { ref: "Isaiah 35:4", text: "Say to those with fearful hearts, 'Be strong, do not fear; your God will come, he will come with vengeance; with divine retribution he will come to save you.'" },
  { ref: "Isaiah 40:8", text: "The grass withers and the flowers fall, but the word of our God endures forever." },
  { ref: "Isaiah 40:11", text: "He tends his flock like a shepherd: He gathers the lambs in his arms and carries them close to his heart; he gently leads those that have young." },
  { ref: "Isaiah 40:28", text: "Do you not know? Have you not heard? The Lord is the everlasting God, the Creator of the ends of the earth. He will not grow tired or weary, and his understanding no one can fathom." },
  { ref: "Isaiah 40:29", text: "He gives strength to the weary and increases the power of the weak." },
  { ref: "Isaiah 40:30", text: "Even youths grow tired and weary, and young men stumble and fall;" },
  { ref: "Isaiah 40:31", text: "but those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint." },
  { ref: "Isaiah 41:10", text: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand." },
  { ref: "Isaiah 41:13", text: "For I am the Lord your God who takes hold of your right hand and says to you, Do not fear; I will help you." },
  { ref: "Isaiah 43:1", text: "Do not fear, for I have redeemed you; I have summoned you by name; you are mine." },
  { ref: "Isaiah 43:2", text: "When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you." },
  { ref: "Isaiah 43:18", text: "Forget the former things; do not dwell on the past." },
  { ref: "Isaiah 43:19", text: "See, I am doing a new thing! Now it springs up; do you not perceive it?" },
  { ref: "Isaiah 44:22", text: "I have swept away your offenses like a cloud, your sins like the morning mist. Return to me, for I have redeemed you." },
  { ref: "Isaiah 45:22", text: "Turn to me and be saved, all you ends of the earth; for I am God, and there is no other." },
  { ref: "Isaiah 46:4", text: "Even to your old age and gray hairs I am he, I am he who will sustain you. I have made you and I will carry you; I will sustain you and I will rescue you." },
  { ref: "Isaiah 48:17", text: "This is what the Lord says—your Redeemer, the Holy One of Israel: 'I am the Lord your God, who teaches you what is best for you, who directs you in the way you should go.'" },
  { ref: "Isaiah 49:13", text: "Shout for joy, you heavens; rejoice, you earth; burst into song, you mountains! For the Lord comforts his people and will have compassion on his afflicted ones." },
  { ref: "Isaiah 53:5", text: "But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed." },
  { ref: "Isaiah 53:6", text: "We all, like sheep, have gone astray, each of us has turned to our own way; and the Lord has laid on him the iniquity of us all." },
  { ref: "Isaiah 54:10", text: "'Though the mountains be shaken and the hills be removed, yet my unfailing love for you will not be shaken nor my covenant of peace be removed,' says the Lord, who has compassion on you." },
  { ref: "Isaiah 54:17", text: "'No weapon forged against you will prevail, and you will refute every tongue that accuses you. This is the heritage of the servants of the Lord, and this is their vindication from me,' declares the Lord." },
  { ref: "Isaiah 55:6", text: "Seek the Lord while he may be found; call on him while he is near." },
  { ref: "Isaiah 55:8", text: "'For my thoughts are not your thoughts, neither are your ways my ways,' declares the Lord." },
  { ref: "Isaiah 55:9", text: "'As the heavens are higher than the earth, so are my ways higher than your ways and my thoughts than your thoughts.'" },
  { ref: "Isaiah 55:11", text: "So is my word that goes out from my mouth: It will not return to me empty, but will accomplish what I desire and achieve the purpose for which I sent it." },
  { ref: "Isaiah 58:11", text: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame. You will be like a well-watered garden, like a spring whose waters never fail." },
  { ref: "Isaiah 60:1", text: "Arise, shine, for your light has come, and the glory of the Lord rises upon you." },
  { ref: "Isaiah 61:1", text: "The Spirit of the Sovereign Lord is on me, because the Lord has anointed me to proclaim good news to the poor." },
  { ref: "Isaiah 61:3", text: "And provide for those who grieve in Zion—to bestow on them a crown of beauty instead of ashes, the oil of joy instead of mourning, and a garment of praise instead of a spirit of despair." },
  { ref: "Isaiah 64:4", text: "Since ancient times no one has heard, no ear has perceived, no eye has seen any God besides you, who acts on behalf of those who wait for him." },
  { ref: "Isaiah 65:24", text: "Before they call I will answer; while they are still speaking I will hear." },
  // Jeremiah
  { ref: "Jeremiah 1:5", text: "Before I formed you in the womb I knew you, before you were born I set you apart; I appointed you as a prophet to the nations." },
  { ref: "Jeremiah 17:7", text: "But blessed is the one who trusts in the Lord, whose confidence is in him." },
  { ref: "Jeremiah 17:8", text: "They will be like a tree planted by the water that sends out its roots by the stream." },
  { ref: "Jeremiah 17:9", text: "The heart is deceitful above all things and beyond cure. Who can understand it?" },
  { ref: "Jeremiah 29:11", text: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future." },
  { ref: "Jeremiah 29:12", text: "Then you will call on me and come and pray to me, and I will listen to you." },
  { ref: "Jeremiah 29:13", text: "You will seek me and find me when you seek me with all your heart." },
  { ref: "Jeremiah 31:3", text: "The Lord appeared to us in the past, saying: 'I have loved you with an everlasting love; I have drawn you with unfailing kindness.'" },
  { ref: "Jeremiah 31:34", text: "For I will forgive their wickedness and will remember their sins no more." },
  { ref: "Jeremiah 33:3", text: "Call to me and I will answer you and tell you great and unsearchable things you do not know." },
  // Lamentations
  { ref: "Lamentations 3:22", text: "Because of the Lord's great love we are not consumed, for his compassions never fail." },
  { ref: "Lamentations 3:23", text: "They are new every morning; great is your faithfulness." },
  { ref: "Lamentations 3:24", text: "I say to myself, 'The Lord is my portion; therefore I will wait for him.'" },
  { ref: "Lamentations 3:25", text: "The Lord is good to those whose hope is in him, to the one who seeks him." },
  // Ezekiel
  { ref: "Ezekiel 36:26", text: "I will give you a new heart and put a new spirit in you; I will remove from you your heart of stone and give you a heart of flesh." },
  { ref: "Ezekiel 37:14", text: "I will put my Spirit in you and you will live, and I will settle you in your own land. Then you will know that I the Lord have spoken, and I have done it, declares the Lord." },
  // Daniel
  { ref: "Daniel 3:17", text: "If we are thrown into the blazing furnace, the God we serve is able to deliver us from it, and he will deliver us from Your Majesty's hand." },
  { ref: "Daniel 6:22", text: "My God sent his angel, and he shut the mouths of the lions. They have not hurt me, because I was found innocent in his sight." },
  { ref: "Daniel 10:19", text: "Do not be afraid, you who are highly esteemed, he said. Peace! Be strong now; be strong. When he spoke to me, I was strengthened." },
  // Hosea
  { ref: "Hosea 6:3", text: "Let us acknowledge the Lord; let us press on to acknowledge him. As surely as the sun rises, he will appear; he will come to us like the winter rains, like the spring rains that water the earth." },
  { ref: "Hosea 14:4", text: "I will heal their waywardness and love them freely, for my anger has turned away from them." },
  // Joel
  { ref: "Joel 2:13", text: "Rend your heart and not your garments. Return to the Lord your God, for he is gracious and compassionate, slow to anger and abounding in love." },
  { ref: "Joel 2:28", text: "And afterward, I will pour out my Spirit on all people. Your sons and daughters will prophesy, your old men will dream dreams, your young men will see visions." },
  // Amos
  { ref: "Amos 5:24", text: "But let justice roll on like a river, righteousness like a never-failing stream!" },
  // Micah
  { ref: "Micah 6:8", text: "He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God." },
  { ref: "Micah 7:7", text: "But as for me, I watch in hope for the Lord, I wait for God my Savior; my God will hear me." },
  // Nahum
  { ref: "Nahum 1:7", text: "The Lord is good, a refuge in times of trouble. He cares for those who trust in him." },
  // Habakkuk
  { ref: "Habakkuk 2:4", text: "The righteous person will live by his faithfulness." },
  { ref: "Habakkuk 3:17", text: "Though the fig tree does not bud and there are no grapes on the vines, though the olive crop fails and the fields produce no food, though there are no sheep in the pen and no cattle in the stalls," },
  { ref: "Habakkuk 3:18", text: "yet I will rejoice in the Lord, I will be joyful in God my Savior." },
  { ref: "Habakkuk 3:19", text: "The Sovereign Lord is my strength; he makes my feet like the feet of a deer, he enables me to tread on the heights." },
  // Zephaniah
  { ref: "Zephaniah 3:17", text: "The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing." },
  // Haggai
  { ref: "Haggai 2:4", text: "But now be strong, Zerubbabel, declares the Lord. Be strong, Joshua son of Jozadak, the high priest. Be strong, all you people of the land, declares the Lord, and work. For I am with you, declares the Lord Almighty." },
  // Zechariah
  { ref: "Zechariah 4:6", text: "'Not by might nor by power, but by my Spirit,' says the Lord Almighty." },
  // Malachi
  { ref: "Malachi 3:6", text: "I the Lord do not change. So you, the descendants of Jacob, are not destroyed." },
  { ref: "Malachi 3:10", text: "Bring the whole tithe into the storehouse, that there may be food in my house. Test me in this, says the Lord Almighty, and see if I will not throw open the floodgates of heaven and pour out so much blessing that there will not be room enough to store it." },
  // Matthew
  { ref: "Matthew 1:23", text: "The virgin will conceive and give birth to a son, and they will call him Immanuel (which means 'God with us')." },
  { ref: "Matthew 4:4", text: "Jesus answered, 'It is written: Man shall not live on bread alone, but on every word that comes from the mouth of God.'" },
  { ref: "Matthew 5:3", text: "Blessed are the poor in spirit, for theirs is the kingdom of heaven." },
  { ref: "Matthew 5:4", text: "Blessed are those who mourn, for they will be comforted." },
  { ref: "Matthew 5:5", text: "Blessed are the meek, for they will inherit the earth." },
  { ref: "Matthew 5:6", text: "Blessed are those who hunger and thirst for righteousness, for they will be filled." },
  { ref: "Matthew 5:7", text: "Blessed are the merciful, for they will be shown mercy." },
  { ref: "Matthew 5:8", text: "Blessed are the pure in heart, for they will see God." },
  { ref: "Matthew 5:9", text: "Blessed are the peacemakers, for they will be called children of God." },
  { ref: "Matthew 5:14", text: "You are the light of the world. A town built on a hill cannot be hidden." },
  { ref: "Matthew 5:16", text: "In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven." },
  { ref: "Matthew 5:44", text: "But I tell you, love your enemies and pray for those who persecute you." },
  { ref: "Matthew 6:9", text: "This, then, is how you should pray: Our Father in heaven, hallowed be your name," },
  { ref: "Matthew 6:10", text: "your kingdom come, your will be done, on earth as it is in heaven." },
  { ref: "Matthew 6:11", text: "Give us today our daily bread." },
  { ref: "Matthew 6:12", text: "And forgive us our debts, as we also have forgiven our debtors." },
  { ref: "Matthew 6:13", text: "And lead us not into temptation, but deliver us from the evil one." },
  { ref: "Matthew 6:19", text: "Do not store up for yourselves treasures on earth, where moths and vermin destroy, and where thieves break in and steal." },
  { ref: "Matthew 6:20", text: "But store up for yourselves treasures in heaven, where moths and vermin do not destroy, and where thieves do not break in and steal." },
  { ref: "Matthew 6:21", text: "For where your treasure is, there your heart will be also." },
  { ref: "Matthew 6:24", text: "No one can serve two masters. Either you will hate the one and love the other, or you will be devoted to the one and despise the other. You cannot serve both God and money." },
  { ref: "Matthew 6:25", text: "Therefore I tell you, do not worry about your life, what you will eat or drink; or about your body, what you will wear. Is not life more than food, and the body more than clothes?" },
  { ref: "Matthew 6:26", text: "Look at the birds of the air; they do not sow or reap or store away in barns, and yet your heavenly Father feeds them. Are you not much more valuable than they?" },
  { ref: "Matthew 6:33", text: "But seek first his kingdom and his righteousness, and all these things will be given to you as well." },
  { ref: "Matthew 6:34", text: "Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own." },
  { ref: "Matthew 7:7", text: "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you." },
  { ref: "Matthew 7:12", text: "So in everything, do to others what you would have them do to you, for this sums up the Law and the Prophets." },
  { ref: "Matthew 7:24", text: "Therefore everyone who hears these words of mine and puts them into practice is like a wise man who built his house on the rock." },
  { ref: "Matthew 9:38", text: "Ask the Lord of the harvest, therefore, to send out workers into his harvest field." },
  { ref: "Matthew 11:28", text: "Come to me, all you who are weary and burdened, and I will give you rest." },
  { ref: "Matthew 11:29", text: "Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls." },
  { ref: "Matthew 11:30", text: "For my yoke is easy and my burden is light." },
  { ref: "Matthew 16:26", text: "What good will it be for someone to gain the whole world, yet forfeit their soul? Or what can anyone give in exchange for their soul?" },
  { ref: "Matthew 17:20", text: "Truly I tell you, if you have faith as small as a mustard seed, you can say to this mountain, 'Move from here to there,' and it will move. Nothing will be impossible for you." },
  { ref: "Matthew 18:20", text: "For where two or three gather in my name, there am I with them." },
  { ref: "Matthew 19:26", text: "Jesus looked at them and said, 'With man this is impossible, but with God all things are possible.'" },
  { ref: "Matthew 22:37", text: "Jesus replied: 'Love the Lord your God with all your heart and with all your soul and with all your mind.'" },
  { ref: "Matthew 22:39", text: "And the second is like it: 'Love your neighbor as yourself.'" },
  { ref: "Matthew 28:19", text: "Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit." },
  { ref: "Matthew 28:20", text: "And teaching them to obey everything I have commanded you. And surely I am with you always, to the very end of the age." },
  // Mark
  { ref: "Mark 1:15", text: "The time has come, he said. The kingdom of God has come near. Repent and believe the good news!" },
  { ref: "Mark 9:23", text: "Everything is possible for one who believes." },
  { ref: "Mark 10:27", text: "Jesus looked at them and said, 'With man this is impossible, but not with God; all things are possible with God.'" },
  { ref: "Mark 10:45", text: "For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many." },
  { ref: "Mark 11:24", text: "Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours." },
  { ref: "Mark 12:30", text: "Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength." },
  { ref: "Mark 16:15", text: "He said to them, 'Go into all the world and preach the gospel to all creation.'" },
  // Luke
  { ref: "Luke 1:37", text: "For no word from God will ever fail." },
  { ref: "Luke 1:45", text: "Blessed is she who has believed that the Lord would fulfill his promises to her!" },
  { ref: "Luke 2:14", text: "Glory to God in the highest heaven, and on earth peace to those on whom his favor rests." },
  { ref: "Luke 4:18", text: "The Spirit of the Lord is on me, because he has anointed me to proclaim good news to the poor." },
  { ref: "Luke 6:27", text: "But to you who are listening I say: Love your enemies, do good to those who hate you." },
  { ref: "Luke 6:31", text: "Do to others as you would have them do to you." },
  { ref: "Luke 6:38", text: "Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap." },
  { ref: "Luke 10:27", text: "He answered, 'Love the Lord your God with all your heart and with all your soul and with all your strength and with all your mind; and, Love your neighbor as yourself.'" },
  { ref: "Luke 11:9", text: "So I say to you: Ask and it will be given to you; seek and you will find; knock and the door will be opened to you." },
  { ref: "Luke 12:7", text: "Indeed, the very hairs of your head are all numbered. Don't be afraid; you are worth more than many sparrows." },
  { ref: "Luke 12:31", text: "But seek his kingdom, and these things will be given to you as well." },
  { ref: "Luke 15:7", text: "I tell you that in the same way there will be more rejoicing in heaven over one sinner who repents than over ninety-nine righteous persons who do not need to repent." },
  { ref: "Luke 18:27", text: "Jesus replied, 'What is impossible with man is possible with God.'" },
  { ref: "Luke 19:10", text: "For the Son of Man came to seek and to save the lost." },
  // John
  { ref: "John 1:1", text: "In the beginning was the Word, and the Word was with God, and the Word was God." },
  { ref: "John 1:12", text: "Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God." },
  { ref: "John 1:14", text: "The Word became flesh and made his dwelling among us. We have seen his glory, the glory of the one and only Son, who came from the Father, full of grace and truth." },
  { ref: "John 3:16", text: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life." },
  { ref: "John 3:17", text: "For God did not send his Son into the world to condemn the world, but to save the world through him." },
  { ref: "John 4:24", text: "God is spirit, and his worshipers must worship in the Spirit and in truth." },
  { ref: "John 6:35", text: "Then Jesus declared, 'I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.'" },
  { ref: "John 6:37", text: "All those the Father gives me will come to me, and whoever comes to me I will never drive away." },
  { ref: "John 6:40", text: "For my Father's will is that everyone who looks to the Son and believes in him shall have eternal life, and I will raise them up at the last day." },
  { ref: "John 8:12", text: "When Jesus spoke again to the people, he said, 'I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.'" },
  { ref: "John 8:32", text: "Then you will know the truth, and the truth will set you free." },
  { ref: "John 8:36", text: "So if the Son sets you free, you will be free indeed." },
  { ref: "John 10:10", text: "The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full." },
  { ref: "John 10:11", text: "I am the good shepherd. The good shepherd lays down his life for the sheep." },
  { ref: "John 10:27", text: "My sheep listen to my voice; I know them, and they follow me." },
  { ref: "John 10:28", text: "I give them eternal life, and they shall never perish; no one will snatch them out of my hand." },
  { ref: "John 11:25", text: "Jesus said to her, 'I am the resurrection and the life. The one who believes in me will live, even though they die.'" },
  { ref: "John 11:26", text: "And whoever lives by believing in me will never die. Do you believe this?" },
  { ref: "John 13:34", text: "A new command I give you: Love one another. As I have loved you, so you must love one another." },
  { ref: "John 13:35", text: "By this everyone will know that you are my disciples, if you love one another." },
  { ref: "John 14:1", text: "Do not let your hearts be troubled. You believe in God; believe also in me." },
  { ref: "John 14:2", text: "My Father's house has many rooms; if that were not so, would I have told you that I am going there to prepare a place for you?" },
  { ref: "John 14:3", text: "And if I go and prepare a place for you, I will come back and take you to be with me that you also may be where I am." },
  { ref: "John 14:6", text: "Jesus answered, 'I am the way and the truth and the life. No one comes to the Father except through me.'" },
  { ref: "John 14:13", text: "And I will do whatever you ask in my name, so that the Father may be glorified in the Son." },
  { ref: "John 14:14", text: "You may ask me for anything in my name, and I will do it." },
  { ref: "John 14:15", text: "If you love me, keep my commands." },
  { ref: "John 14:16", text: "And I will ask the Father, and he will give you another advocate to help you and be with you forever." },
  { ref: "John 14:26", text: "But the Advocate, the Holy Spirit, whom the Father will send in my name, will teach you all things and will remind you of everything I have said to you." },
  { ref: "John 14:27", text: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid." },
  { ref: "John 15:5", text: "I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing." },
  { ref: "John 15:7", text: "If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you." },
  { ref: "John 15:12", text: "My command is this: Love each other as I have loved you." },
  { ref: "John 15:13", text: "Greater love has no one than this: to lay down one's life for one's friends." },
  { ref: "John 15:16", text: "You did not choose me, but I chose you and appointed you so that you might go and bear fruit—fruit that will last." },
  { ref: "John 16:13", text: "But when he, the Spirit of truth, comes, he will guide you into all the truth." },
  { ref: "John 16:33", text: "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world." },
  // Acts
  { ref: "Acts 1:8", text: "But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth." },
  { ref: "Acts 2:17", text: "In the last days, God says, I will pour out my Spirit on all people. Your sons and daughters will prophesy, your young men will see visions, your old men will dream dreams." },
  { ref: "Acts 2:38", text: "Peter replied, 'Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins. And you will receive the gift of the Holy Spirit.'" },
  { ref: "Acts 2:44", text: "All the believers were together and had everything in common." },
  { ref: "Acts 4:12", text: "Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved." },
  { ref: "Acts 4:31", text: "After they prayed, the place where they were meeting was shaken. And they were all filled with the Holy Spirit and spoke the word of God boldly." },
  { ref: "Acts 16:31", text: "They replied, 'Believe in the Lord Jesus, and you will be saved—you and your household.'" },
  { ref: "Acts 20:35", text: "It is more blessed to give than to receive." },
  // Romans
  { ref: "Romans 1:16", text: "For I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes." },
  { ref: "Romans 3:23", text: "For all have sinned and fall short of the glory of God." },
  { ref: "Romans 3:24", text: "and all are justified freely by his grace through the redemption that came by Christ Jesus." },
  { ref: "Romans 4:20", text: "Yet he did not waver through unbelief regarding the promise of God, but was strengthened in his faith and gave glory to God." },
  { ref: "Romans 5:1", text: "Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ." },
  { ref: "Romans 5:3", text: "Not only so, but we also glory in our sufferings, because we know that suffering produces perseverance;" },
  { ref: "Romans 5:4", text: "perseverance, character; and character, hope." },
  { ref: "Romans 5:5", text: "And hope does not put us to shame, because God's love has been poured out into our hearts through the Holy Spirit, who has been given to us." },
  { ref: "Romans 5:8", text: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us." },
  { ref: "Romans 6:23", text: "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord." },
  { ref: "Romans 8:1", text: "Therefore, there is now no condemnation for those who are in Christ Jesus." },
  { ref: "Romans 8:11", text: "And if the Spirit of him who raised Jesus from the dead is living in you, he who raised Christ from the dead will also give life to your mortal bodies because of his Spirit who lives in you." },
  { ref: "Romans 8:17", text: "Now if we are children, then we are heirs—heirs of God and co-heirs with Christ, if indeed we share in his sufferings in order that we may also share in his glory." },
  { ref: "Romans 8:18", text: "I consider that our present sufferings are not worth comparing with the glory that will be revealed in us." },
  { ref: "Romans 8:26", text: "In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans." },
  { ref: "Romans 8:28", text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose." },
  { ref: "Romans 8:31", text: "What, then, shall we say in response to these things? If God is for us, who can be against us?" },
  { ref: "Romans 8:32", text: "He who did not spare his own Son, but gave him up for us all—how will he not also, along with him, graciously give us all things?" },
  { ref: "Romans 8:37", text: "No, in all these things we are more than conquerors through him who loved us." },
  { ref: "Romans 8:38", text: "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers," },
  { ref: "Romans 8:39", text: "neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord." },
  { ref: "Romans 10:9", text: "If you declare with your mouth, 'Jesus is Lord,' and believe in your heart that God raised him from the dead, you will be saved." },
  { ref: "Romans 10:10", text: "For it is with your heart that you believe and are justified, and it is with your mouth that you profess your faith and are saved." },
  { ref: "Romans 10:13", text: "For, 'Everyone who calls on the name of the Lord will be saved.'" },
  { ref: "Romans 10:17", text: "Consequently, faith comes from hearing the message, and the message is heard through the word about Christ." },
  { ref: "Romans 12:1", text: "Therefore, I urge you, brothers and sisters, in view of God's mercy, to offer your bodies as a living sacrifice, holy and pleasing to God—this is your true and proper worship." },
  { ref: "Romans 12:2", text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God's will is—his good, pleasing and perfect will." },
  { ref: "Romans 12:9", text: "Love must be sincere. Hate what is evil; cling to what is good." },
  { ref: "Romans 12:10", text: "Be devoted to one another in love. Honor one another above yourselves." },
  { ref: "Romans 12:12", text: "Be joyful in hope, patient in affliction, faithful in prayer." },
  { ref: "Romans 12:18", text: "If it is possible, as far as it depends on you, live at peace with everyone." },
  { ref: "Romans 12:19", text: "Do not take revenge, my dear friends, but leave room for God's wrath, for it is written: 'It is mine to avenge; I will repay,' says the Lord." },
  { ref: "Romans 12:21", text: "Do not be overcome by evil, but overcome evil with good." },
  { ref: "Romans 15:4", text: "For everything that was written in the past was written to teach us, so that through the endurance taught in the Scriptures and the encouragement they provide we might have hope." },
  { ref: "Romans 15:13", text: "May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit." },
  // 1 Corinthians
  { ref: "1 Corinthians 1:18", text: "For the message of the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God." },
  { ref: "1 Corinthians 2:9", text: "However, as it is written: 'What no eye has seen, what no ear has heard, and what no human mind has conceived — the things God has prepared for those who love him.'" },
  { ref: "1 Corinthians 3:16", text: "Don't you know that you yourselves are God's temple and that God's Spirit dwells in your midst?" },
  { ref: "1 Corinthians 4:20", text: "For the kingdom of God is not a matter of talk but of power." },
  { ref: "1 Corinthians 6:19", text: "Do you not know that your bodies are temples of the Holy Spirit, who is in you, whom you have received from God? You are not your own;" },
  { ref: "1 Corinthians 6:20", text: "you were bought at a price. Therefore honor God with your bodies." },
  { ref: "1 Corinthians 10:13", text: "No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear." },
  { ref: "1 Corinthians 13:1", text: "If I speak in the tongues of men or of angels, but do not have love, I am only a resounding gong or a clanging cymbal." },
  { ref: "1 Corinthians 13:2", text: "If I have the gift of prophecy and can fathom all mysteries and all knowledge, and if I have a faith that can move mountains, but do not have love, I am nothing." },
  { ref: "1 Corinthians 13:3", text: "If I give all I possess to the poor and give over my body to hardship that I may boast, but do not have love, I gain nothing." },
  { ref: "1 Corinthians 13:4", text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud." },
  { ref: "1 Corinthians 13:5", text: "It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs." },
  { ref: "1 Corinthians 13:6", text: "Love does not delight in evil but rejoices with the truth." },
  { ref: "1 Corinthians 13:7", text: "It always protects, always trusts, always hopes, always perseveres." },
  { ref: "1 Corinthians 13:8", text: "Love never fails. But where there are prophecies, they will cease; where there are tongues, they will be stilled; where there is knowledge, it will pass away." },
  { ref: "1 Corinthians 13:13", text: "And now these three remain: faith, hope and love. But the greatest of these is love." },
  { ref: "1 Corinthians 15:3", text: "For what I received I passed on to you as of first importance: that Christ died for our sins according to the Scriptures." },
  { ref: "1 Corinthians 15:4", text: "that he was buried, that he was raised on the third day according to the Scriptures." },
  { ref: "1 Corinthians 15:10", text: "But by the grace of God I am what I am, and his grace to me was not without effect." },
  { ref: "1 Corinthians 15:22", text: "For as in Adam all die, so in Christ all will be made alive." },
  { ref: "1 Corinthians 15:55", text: "Where, O death, is your victory? Where, O death, is your sting?" },
  { ref: "1 Corinthians 15:57", text: "But thanks be to God! He gives us the victory through our Lord Jesus Christ." },
  { ref: "1 Corinthians 15:58", text: "Therefore, my dear brothers and sisters, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain." },
  // 2 Corinthians
  { ref: "2 Corinthians 1:3", text: "Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort." },
  { ref: "2 Corinthians 1:4", text: "who comforts us in all our troubles, so that we can comfort those in any trouble with the comfort we ourselves receive from God." },
  { ref: "2 Corinthians 4:7", text: "But we have this treasure in jars of clay to show that this all-surpassing power is from God and not from us." },
  { ref: "2 Corinthians 4:8", text: "We are hard pressed on every side, but not crushed; perplexed, but not in despair;" },
  { ref: "2 Corinthians 4:9", text: "persecuted, but not abandoned; struck down, but not destroyed." },
  { ref: "2 Corinthians 4:16", text: "Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day." },
  { ref: "2 Corinthians 4:17", text: "For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all." },
  { ref: "2 Corinthians 4:18", text: "So we fix our eyes not on what is seen, but on what is unseen, since what is seen is temporary, but what is unseen is eternal." },
  { ref: "2 Corinthians 5:7", text: "For we live by faith, not by sight." },
  { ref: "2 Corinthians 5:17", text: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!" },
  { ref: "2 Corinthians 5:21", text: "God made him who had no sin to be sin for us, so that in him we might become the righteousness of God." },
  { ref: "2 Corinthians 6:2", text: "For he says, 'In the time of my favor I heard you, and in the day of salvation I helped you.' I tell you, now is the time of God's favor, now is the day of salvation." },
  { ref: "2 Corinthians 9:6", text: "Remember this: Whoever sows sparingly will also reap sparingly, and whoever sows generously will also reap generously." },
  { ref: "2 Corinthians 9:7", text: "Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver." },
  { ref: "2 Corinthians 9:8", text: "And God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work." },
  { ref: "2 Corinthians 10:4", text: "The weapons we fight with are not the weapons of the world. On the contrary, they have divine power to demolish strongholds." },
  { ref: "2 Corinthians 12:9", text: "But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.'" },
  { ref: "2 Corinthians 12:10", text: "That is why, for Christ's sake, I delight in weaknesses, in insults, in hardships, in persecutions, in difficulties. For when I am weak, then I am strong." },
  // Galatians
  { ref: "Galatians 2:20", text: "I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me." },
  { ref: "Galatians 3:26", text: "So in Christ Jesus you are all children of God through faith." },
  { ref: "Galatians 3:28", text: "There is neither Jew nor Gentile, neither slave nor free, nor is there male and female, for you are all one in Christ Jesus." },
  { ref: "Galatians 5:1", text: "It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery." },
  { ref: "Galatians 5:13", text: "You, my brothers and sisters, were called to be free. But do not use your freedom to indulge the flesh; rather, serve one another humbly in love." },
  { ref: "Galatians 5:14", text: "For the entire law is fulfilled in keeping this one command: 'Love your neighbor as yourself.'" },
  { ref: "Galatians 5:22", text: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness," },
  { ref: "Galatians 5:23", text: "gentleness and self-control. Against such things there is no law." },
  { ref: "Galatians 6:2", text: "Carry each other's burdens, and in this way you will fulfill the law of Christ." },
  { ref: "Galatians 6:7", text: "Do not be deceived: God cannot be mocked. A man reaps what he sows." },
  { ref: "Galatians 6:9", text: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up." },
  // Ephesians
  { ref: "Ephesians 1:3", text: "Praise be to the God and Father of our Lord Jesus Christ, who has blessed us in the heavenly realms with every spiritual blessing in Christ." },
  { ref: "Ephesians 1:11", text: "In him we were also chosen, having been predestined according to the plan of him who works out everything in conformity with the purpose of his will." },
  { ref: "Ephesians 2:4", text: "But because of his great love for us, God, who is rich in mercy," },
  { ref: "Ephesians 2:5", text: "made us alive with Christ even when we were dead in transgressions—it is by grace you have been saved." },
  { ref: "Ephesians 2:8", text: "For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God—" },
  { ref: "Ephesians 2:9", text: "not by works, so that no one can boast." },
  { ref: "Ephesians 2:10", text: "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do." },
  { ref: "Ephesians 3:16", text: "I pray that out of his glorious riches he may strengthen you with power through his Spirit in your inner being." },
  { ref: "Ephesians 3:17", text: "so that Christ may dwell in your hearts through faith. And I pray that you, being rooted and established in love." },
  { ref: "Ephesians 3:20", text: "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us." },
  { ref: "Ephesians 4:2", text: "Be completely humble and gentle; be patient, bearing with one another in love." },
  { ref: "Ephesians 4:29", text: "Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up according to their needs, that it may benefit those who listen." },
  { ref: "Ephesians 4:32", text: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you." },
  { ref: "Ephesians 5:1", text: "Follow God's example, therefore, as dearly loved children." },
  { ref: "Ephesians 5:2", text: "and walk in the way of love, just as Christ loved us and gave himself up for us as a fragrant offering and sacrifice to God." },
  { ref: "Ephesians 5:20", text: "always giving thanks to God the Father for everything, in the name of our Lord Jesus Christ." },
  { ref: "Ephesians 6:10", text: "Finally, be strong in the Lord and in his mighty power." },
  { ref: "Ephesians 6:11", text: "Put on the full armor of God, so that you can take your stand against the devil's schemes." },
  { ref: "Ephesians 6:12", text: "For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world." },
  { ref: "Ephesians 6:17", text: "Take the helmet of salvation and the sword of the Spirit, which is the word of God." },
  { ref: "Ephesians 6:18", text: "And pray in the Spirit on all occasions with all kinds of prayers and requests." },
  // Philippians
  { ref: "Philippians 1:6", text: "Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus." },
  { ref: "Philippians 1:21", text: "For to me, to live is Christ and to die is gain." },
  { ref: "Philippians 2:3", text: "Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves." },
  { ref: "Philippians 2:4", text: "Not looking to your own interests but each of you to the interests of the others." },
  { ref: "Philippians 2:13", text: "For it is God who works in you to will and to act in order to fulfill his good purpose." },
  { ref: "Philippians 3:13", text: "Brothers and sisters, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead." },
  { ref: "Philippians 3:14", text: "I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus." },
  { ref: "Philippians 4:4", text: "Rejoice in the Lord always. I will say it again: Rejoice!" },
  { ref: "Philippians 4:6", text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God." },
  { ref: "Philippians 4:7", text: "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus." },
  { ref: "Philippians 4:8", text: "Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things." },
  { ref: "Philippians 4:11", text: "I have learned, in whatever state I am, to be content." },
  { ref: "Philippians 4:12", text: "I know what it is to be in need, and I know what it is to have plenty. I have learned the secret of being content in any and every situation." },
  { ref: "Philippians 4:13", text: "I can do all this through him who gives me strength." },
  { ref: "Philippians 4:19", text: "And my God will meet all your needs according to the riches of his glory in Christ Jesus." },
  // Colossians
  { ref: "Colossians 1:16", text: "For in him all things were created: things in heaven and on earth, visible and invisible, whether thrones or powers or rulers or authorities; all things have been created through him and for him." },
  { ref: "Colossians 1:17", text: "He is before all things, and in him all things hold together." },
  { ref: "Colossians 3:1", text: "Since, then, you have been raised with Christ, set your hearts on things above, where Christ is, seated at the right hand of God." },
  { ref: "Colossians 3:2", text: "Set your minds on things above, not on earthly things." },
  { ref: "Colossians 3:12", text: "Therefore, as God's chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience." },
  { ref: "Colossians 3:13", text: "Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you." },
  { ref: "Colossians 3:14", text: "And over all these virtues put on love, which binds them all together in perfect unity." },
  { ref: "Colossians 3:15", text: "Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful." },
  { ref: "Colossians 3:16", text: "Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom." },
  { ref: "Colossians 3:23", text: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters." },
  // 1 Thessalonians
  { ref: "1 Thessalonians 4:13", text: "Brothers and sisters, we do not want you to be uninformed about those who sleep in death, so that you do not grieve like the rest of mankind, who have no hope." },
  { ref: "1 Thessalonians 5:11", text: "Therefore encourage one another and build each other up, just as in fact you are doing." },
  { ref: "1 Thessalonians 5:16", text: "Rejoice always," },
  { ref: "1 Thessalonians 5:17", text: "pray continually," },
  { ref: "1 Thessalonians 5:18", text: "give thanks in all circumstances; for this is God's will for you in Christ Jesus." },
  // 2 Thessalonians
  { ref: "2 Thessalonians 3:3", text: "But the Lord is faithful, and he will strengthen you and protect you from the evil one." },
  // 1 Timothy
  { ref: "1 Timothy 1:15", text: "Here is a trustworthy saying that deserves full acceptance: Christ Jesus came into the world to save sinners—of whom I am the worst." },
  { ref: "1 Timothy 4:8", text: "For physical training is of some value, but godliness has value for all things, holding promise for both the present life and the life to come." },
  { ref: "1 Timothy 6:6", text: "But godliness with contentment is great gain." },
  { ref: "1 Timothy 6:7", text: "For we brought nothing into the world, and we can take nothing out of it." },
  { ref: "1 Timothy 6:10", text: "For the love of money is a root of all kinds of evil. Some people, eager for money, have wandered from the faith and pierced themselves with many griefs." },
  { ref: "1 Timothy 6:12", text: "Fight the good fight of the faith. Take hold of the eternal life to which you were called when you made your good confession in the presence of many witnesses." },
  // 2 Timothy
  { ref: "2 Timothy 1:7", text: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline." },
  { ref: "2 Timothy 2:15", text: "Do your best to present yourself to God as one approved, a worker who does not need to be ashamed and who correctly handles the word of truth." },
  { ref: "2 Timothy 3:16", text: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness." },
  { ref: "2 Timothy 3:17", text: "so that the servant of God may be thoroughly equipped for every good work." },
  { ref: "2 Timothy 4:7", text: "I have fought the good fight, I have finished the race, I have kept the faith." },
  // Titus
  { ref: "Titus 2:11", text: "For the grace of God has appeared that offers salvation to all people." },
  { ref: "Titus 3:5", text: "He saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewing by the Holy Spirit." },
  // Philemon
  { ref: "Philemon 1:6", text: "I pray that your partnership with us in the faith may be effective in deepening your understanding of every good thing we share for the sake of Christ." },
  // Hebrews
  { ref: "Hebrews 1:3", text: "The Son is the radiance of God's glory and the exact representation of his being, sustaining all things by his powerful word." },
  { ref: "Hebrews 4:12", text: "For the word of God is alive and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart." },
  { ref: "Hebrews 4:15", text: "For we do not have a high priest who is unable to empathize with our weaknesses, but we have one who has been tempted in every way, just as we are—yet he did not sin." },
  { ref: "Hebrews 4:16", text: "Let us then approach God's throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need." },
  { ref: "Hebrews 6:19", text: "We have this hope as an anchor for the soul, firm and secure." },
  { ref: "Hebrews 10:23", text: "Let us hold unswervingly to the hope we profess, for he who promised is faithful." },
  { ref: "Hebrews 10:24", text: "And let us consider how we may spur one another on toward love and good deeds." },
  { ref: "Hebrews 10:25", text: "Not giving up meeting together, as some are in the habit of doing, but encouraging one another." },
  { ref: "Hebrews 11:1", text: "Now faith is confidence in what we hope for and assurance about what we do not see." },
  { ref: "Hebrews 11:6", text: "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him." },
  { ref: "Hebrews 12:1", text: "Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us." },
  { ref: "Hebrews 12:2", text: "Fixing our eyes on Jesus, the pioneer and perfecter of faith. For the joy set before him he endured the cross, scorning its shame, and sat down at the right hand of the throne of God." },
  { ref: "Hebrews 13:5", text: "Keep your lives free from the love of money and be content with what you have, because God has said, 'Never will I leave you; never will I forsake you.'" },
  { ref: "Hebrews 13:6", text: "So we say with confidence, 'The Lord is my helper; I will not be afraid. What can mere mortals do to me?'" },
  { ref: "Hebrews 13:8", text: "Jesus Christ is the same yesterday and today and forever." },
  // James
  { ref: "James 1:2", text: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds." },
  { ref: "James 1:3", text: "Because you know that the testing of your faith produces perseverance." },
  { ref: "James 1:4", text: "Let perseverance finish its work so that you may be mature and complete, not lacking anything." },
  { ref: "James 1:5", text: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you." },
  { ref: "James 1:17", text: "Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows." },
  { ref: "James 1:19", text: "My dear brothers and sisters, take note of this: Everyone should be quick to listen, slow to speak and slow to become angry." },
  { ref: "James 1:22", text: "Do not merely listen to the word, and so deceive yourselves. Do what it says." },
  { ref: "James 2:14", text: "What good is it, my brothers and sisters, if someone claims to have faith but has no deeds? Can such faith save them?" },
  { ref: "James 2:17", text: "In the same way, faith by itself, if it is not accompanied by action, is dead." },
  { ref: "James 4:7", text: "Submit yourselves, then, to God. Resist the devil, and he will flee from you." },
  { ref: "James 4:8", text: "Come near to God and he will come near to you." },
  { ref: "James 4:10", text: "Humble yourselves before the Lord, and he will lift you up." },
  { ref: "James 5:13", text: "Is anyone among you in trouble? Let them pray. Is anyone happy? Let them sing songs of praise." },
  { ref: "James 5:16", text: "Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective." },
  // 1 Peter
  { ref: "1 Peter 1:3", text: "Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead." },
  { ref: "1 Peter 2:9", text: "But you are a chosen people, a royal priesthood, a holy nation, God's special possession, that you may declare the praises of him who called you out of darkness into his wonderful light." },
  { ref: "1 Peter 2:24", text: "He himself bore our sins in his body on the cross, so that we might die to sins and live for righteousness; by his wounds you have been healed." },
  { ref: "1 Peter 3:15", text: "But in your hearts revere Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have." },
  { ref: "1 Peter 4:8", text: "Above all, love each other deeply, because love covers over a multitude of sins." },
  { ref: "1 Peter 5:6", text: "Humble yourselves, therefore, under God's mighty hand, that he may lift you up in due time." },
  { ref: "1 Peter 5:7", text: "Cast all your anxiety on him because he cares for you." },
  { ref: "1 Peter 5:8", text: "Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion looking for someone to devour." },
  { ref: "1 Peter 5:10", text: "And the God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you and make you strong, firm and steadfast." },
  // 2 Peter
  { ref: "2 Peter 1:3", text: "His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness." },
  { ref: "2 Peter 3:9", text: "The Lord is not slow in keeping his promise, as some understand slowness. Instead he is patient with you, not wanting anyone to perish, but everyone to come to repentance." },
  // 1 John
  { ref: "1 John 1:7", text: "But if we walk in the light, as he is in the light, we have fellowship with one another, and the blood of Jesus, his Son, purifies us from all sin." },
  { ref: "1 John 1:9", text: "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness." },
  { ref: "1 John 2:15", text: "Do not love the world or anything in the world. If anyone loves the world, love for the Father is not in them." },
  { ref: "1 John 3:1", text: "See what great love the Father has lavished on us, that we should be called children of God! And that is what we are!" },
  { ref: "1 John 3:16", text: "This is how we know what love is: Jesus Christ laid down his life for us. And we ought to lay down our lives for our brothers and sisters." },
  { ref: "1 John 3:18", text: "Dear children, let us not love with words or speech but with actions and in truth." },
  { ref: "1 John 4:4", text: "You, dear children, are from God and have overcome them, because the one who is in you is greater than the one who is in the world." },
  { ref: "1 John 4:7", text: "Dear friends, let us love one another, for love comes from God. Everyone who loves has been born of God and knows God." },
  { ref: "1 John 4:8", text: "Whoever does not love does not know God, because God is love." },
  { ref: "1 John 4:9", text: "This is how God showed his love among us: He sent his one and only Son into the world that we might live through him." },
  { ref: "1 John 4:10", text: "This is love: not that we loved God, but that he loved us and sent his Son as an atoning sacrifice for our sins." },
  { ref: "1 John 4:16", text: "And so we know and rely on the love God has for us. God is love. Whoever lives in love lives in God, and God in them." },
  { ref: "1 John 4:18", text: "There is no fear in love. But perfect love drives out fear, because fear has to do with punishment. The one who fears is not made perfect in love." },
  { ref: "1 John 4:19", text: "We love because he first loved us." },
  { ref: "1 John 5:4", text: "For everyone born of God overcomes the world. This is the victory that has overcome the world, even our faith." },
  { ref: "1 John 5:14", text: "This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us." },
  // 2 John
  { ref: "2 John 1:6", text: "And this is love: that we walk in obedience to his commands. As you have heard from the beginning, his command is that you walk in love." },
  // 3 John
  { ref: "3 John 1:2", text: "Dear friend, I pray that you may enjoy good health and that all may go well with you, even as your soul is getting along well." },
  // Jude
  { ref: "Jude 1:20", text: "But you, dear friends, by building yourselves up in your most holy faith and praying in the Holy Spirit." },
  { ref: "Jude 1:24", text: "To him who is able to keep you from stumbling and to present you before his glorious presence without fault and with great joy." },
  // Revelation
  { ref: "Revelation 1:8", text: "'I am the Alpha and the Omega,' says the Lord God, 'who is, and who was, and who is to come, the Almighty.'" },
  { ref: "Revelation 2:10", text: "Do not be afraid of what you are about to suffer. I tell you, the devil will put some of you in prison to test you, and you will suffer persecution for ten days. Be faithful, even to the point of death, and I will give you life as your victor's crown." },
  { ref: "Revelation 3:20", text: "Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me." },
  { ref: "Revelation 4:11", text: "You are worthy, our Lord and God, to receive glory and honor and power, for you created all things, and by your will they were created and have their being." },
  { ref: "Revelation 7:17", text: "For the Lamb at the center of the throne will be their shepherd; he will lead them to springs of living water. And God will wipe away every tear from their eyes." },
  { ref: "Revelation 11:15", text: "The kingdom of the world has become the kingdom of our Lord and of his Messiah, and he will reign for ever and ever." },
  { ref: "Revelation 19:6", text: "Then I heard what sounded like a great multitude, like the roar of rushing waters and like loud peals of thunder, shouting: 'Hallelujah! For our Lord God Almighty reigns.'" },
  { ref: "Revelation 21:1", text: "Then I saw a new heaven and a new earth, for the first heaven and the first earth had passed away, and there was no longer any sea." },
  { ref: "Revelation 21:3", text: "And I heard a loud voice from the throne saying, 'Look! God's dwelling place is now among the people, and he will dwell with them. They will be his people, and God himself will be with them and be their God.'" },
  { ref: "Revelation 21:4", text: "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away." },
  { ref: "Revelation 21:5", text: "He who was seated on the throne said, 'I am making everything new!'" },
  { ref: "Revelation 22:13", text: "I am the Alpha and the Omega, the First and the Last, the Beginning and the End." },
  { ref: "Revelation 22:20", text: "He who testifies to these things says, 'Yes, I am coming soon.' Amen. Come, Lord Jesus." },
  { ref: "Revelation 22:21", text: "The grace of the Lord Jesus be with God's people. Amen." },
];

export default {
  data: new SlashCommandBuilder()
    .setName('bible')
    .setDescription('Get a random Bible verse from across the whole Scripture!')
    .addStringOption(option =>
      option
        .setName('book')
        .setDescription('Search for a specific book (e.g. John, Psalms, Romans)')
        .setRequired(false)
    ),
  category: 'Fun',

  async execute(interaction) {
    await InteractionHelper.safeDefer(interaction);

    const bookQuery = interaction.options.getString('book')?.toLowerCase().trim();
    let pool = VERSES;

    if (bookQuery) {
      pool = VERSES.filter(v => v.ref.toLowerCase().startsWith(bookQuery));
      if (!pool.length) {
        // Try partial match
        pool = VERSES.filter(v => v.ref.toLowerCase().includes(bookQuery));
      }
    }

    if (!pool.length) {
      return InteractionHelper.safeEditReply(interaction, {
        embeds: [
          createEmbed({
            title: '📖 Bible',
            description: `No verses found for **${interaction.options.getString('book')}**. Try a book like \`John\`, \`Psalms\`, or \`Romans\`.`,
            color: 'error',
          }),
        ],
      });
    }

    const verse = pool[Math.floor(Math.random() * pool.length)];

    await InteractionHelper.safeEditReply(interaction, {
      embeds: [
        createEmbed({
          title: `📖 ${verse.ref}`,
          description: `*"${verse.text}"*`,
          color: 'primary',
          footer: { text: `${pool.length === VERSES.length ? `${VERSES.length} verses across all books` : `${pool.length} verse(s) found`} • NIV` },
        }),
      ],
    });
  },
};
