import { SlashCommandBuilder } from 'discord.js';
import { createEmbed } from '../../utils/embeds.js';
import { InteractionHelper } from '../../utils/interactionHelper.js';

const JOKES = [
  "Why don't scientists trust atoms? Because they make up everything.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why can't you give Elsa a balloon? She'll let it go.",
  "I'm reading a book about anti-gravity. It's impossible to put down.",
  "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
  "Why do cows wear bells? Because their horns don't work.",
  "What do you call a fake noodle? An impasta.",
  "How do you organize a space party? You planet.",
  "Why did the scarecrow win an award? He was outstanding in his field.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "I used to hate facial hair, but then it grew on me.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why did the bicycle fall over? It was two-tired.",
  "What do you get when you cross a snowman and a vampire? Frostbite.",
  "I would tell you a construction joke, but I'm still working on it.",
  "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
  "What do you call a sleeping dinosaur? A dino-snore.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "How does a penguin build its house? Igloos it together.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "Why can't Elsa have a balloon? She always lets it go.",
  "What do you call a fish without eyes? A fsh.",
  "Why did the cookie go to the doctor? It was feeling crumby.",
  "What do you call a lazy kangaroo? A pouch potato.",
  "I told my doctor I broke my arm in two places. He told me to stop going to those places.",
  "What do you call an alligator in a vest? An investigator.",
  "Why did the math book look so sad? It had too many problems.",
  "What do you call a man with a rubber toe? Roberto.",
  "Why did the banana go to the doctor? It wasn't peeling well.",
  "What do you call a dog that does magic tricks? A labracadabrador.",
  "Why did the coffee file a police report? It got mugged.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "What do you call a bear with no ears? B.",
  "Why did the gym close down? It just didn't work out.",
  "What do you call a pile of cats? A meow-ntain.",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why did the stadium get hot after the game? All the fans left.",
  "What do you call a guy who's always in debt? Bill.",
  "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
  "What do you call a sleeping bull? A bulldozer.",
  "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
  "What do you call a musician who can't play guitar? A bass-case.",
  "Why are ghosts bad liars? You can see right through them.",
  "What do you call a pig that does karate? A pork chop.",
  "Why did the teacher wear sunglasses? She had bright students.",
  "What do you call a dog that can tell time? A watchdog.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call a naughty lamb? A baaaad kid.",
  "Why is a banana better than a straight one? Because it's a-peeling.",
  "What do you call an owl who does magic? Hoo-dini.",
  "Why did the calendar go to school? To improve its dates.",
  "What do you call a spider on a computer? A web developer.",
  "Why did the shoe go to therapy? It had too many problems with its sole.",
  "What do you call a belt made of watches? A waist of time.",
  "Why did the bird go to the hospital? For tweetment.",
  "What do you call a fake stone? A shamrock.",
  "Why did the nurse need a red pen? In case she needed to draw blood.",
  "What do you call a cat that gets everything it wants? Purrsuasive.",
  "Why did the computer go to the doctor? It had a virus.",
  "What do you call a monkey in a minefield? A baboom.",
  "Why did the man put his money in the freezer? He wanted cold hard cash.",
  "What do you call a broken can opener? A can't opener.",
  "Why was the broom late? It overswept.",
  "What do you call a rabbit comedian? A funny bunny.",
  "Why did the teddy bear say no to dessert? She was already stuffed.",
  "What do you call a nosy pepper? Jalapeño business.",
  "Why did the lamp fail the test? He wasn't very bright.",
  "What do you call a sleeping T-Rex? A dino-snore.",
  "Why did the toilet paper roll down the hill? To get to the bottom.",
  "What do you call a knight who's afraid to fight? Sir Render.",
  "Why did the clock get kicked out of school? It tocked too much.",
  "What do you call a sad strawberry? A blueberry.",
  "Why did the skeleton go to the party alone? He had no body to go with.",
  "What do you call an honest person? An oxymoron.",
  "Why did the biscuit cry? His mum had been a wafer so long.",
  "What do you call a camel with no humps? Humphrey.",
  "Why did the orange stop rolling down the hill? It ran out of juice.",
  "What do you call a line of men waiting for a haircut? A barber-queue.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a cow in an earthquake? A milkshake.",
  "Why did the scarecrow become a successful politician? He was outstanding in his field.",
  "What do you call a baby computer? A micro-chip.",
  "Why did the bicycle need training wheels? It was two-tired.",
  "What do you call a seagull that flies over the bay? A bagel.",
  "Why did the boy eat his homework? Because his teacher told him it was a piece of cake.",
  "What do you call a belt made of hundred-dollar bills? A money belt.",
  "Why was the math test sad? It had too many problems.",
  "What do you call a person who tells bad cat jokes? A pun-isher.",
  "Why did the painter go to jail? He was framed.",
  "What do you call a cow who plays guitar? A moo-sician.",
  "Why is the ocean always on time? It likes to stay current.",
  "What do you call a potato in space? A spud-nik.",
  "Why did the chicken cross the playground? To get to the other slide.",
  "What do you call cheese that's not yours? Not-cho cheese.",
  "Why did the baker go bankrupt? He ran out of dough.",
  "What do you call a sad horse? A glum pony.",
  "Why did the music teacher go to jail? For fingering A minor.",
  "What do you call a penguin in the Sahara? Lost.",
  "Why did the bucket go to therapy? It had a list of issues.",
  "What do you call a witch on the beach? A sand-witch.",
  "Why did the frog take the bus? His car was toad.",
  "What do you call a group of whales? An orca-stra.",
  "Why did the shoe cry? Its tongue was tied.",
  "What do you call a panda who can't keep secrets? Pandascrete.",
  "Why did the tomato blush? It saw the salad dressing.",
  "What do you call a shoe made from a banana? A slipper.",
  "Why did the bread go to the doctor? It was feeling crumby.",
  "What do you call a meerkat in space? An astro-meerkat.",
  "Why did the ant cross the road? To visit his aunts.",
  "What do you call a duck that steals? A robber duck.",
  "Why did the moon skip its meal? It was full.",
  "What do you call an overweight pumpkin? A plump-kin.",
  "Why did the train sneeze? It had a loco-motion.",
  "What do you call a bear in the rain? A drizzly bear.",
  "Why did the egg go to school? To get egg-ucated.",
  "What do you call a donkey with wings? A smart ass.",
  "Why did the butcher work overtime? To make ends meat.",
  "What do you call a lazy elevator? An escalator.",
  "Why did the river never get in trouble? It stayed in its banks.",
  "What do you call a pony with a cough? A little hoarse.",
  "Why did the duck hide his bill? He was being fowl.",
  "What do you call a Frenchman wearing sandals? Philippe Phillope.",
  "Why did the man name his dog Carpenter? Because he did odd jobs around the house.",
  "What do you call a sleeping pizza? A piZZZZZa.",
  "Why did the computer keep sneezing? It had a Windows virus.",
  "What do you call a dog who works for the post office? A lab-rador mailman.",
  "Why did the vegetable go to the doctor? Because it was a sick beet.",
  "What do you call a cow with two legs? Lean beef.",
  "Why did the bird get a job at the bakery? It was good at tweeting.",
  "What do you call a nervous javelin thrower? Shakespeare.",
  "Why did the house go to the doctor? It had a window pane.",
  "What do you call a fish that practices medicine? A sturgeon.",
  "Why did the chef get promoted? He had great thyme management.",
  "What do you call a dinosaur that crashes their car? Tyrannosaurus wrecks.",
  "Why did the farmer win an award? He was outstanding in his field.",
  "What do you call a can opener that doesn't work? A can't opener.",
  "Why did the grape stop in the middle of the road? Because it ran out of juice.",
  "What do you call a boomerang that doesn't come back? A stick.",
  "Why was the math book always unhappy? It had too many problems.",
  "What do you call a polar bear in Hawaii? Lost.",
  "Why did the jelly roll? Because it saw the apple turnover.",
  "What do you call a fish with no eyes? A fsh.",
  "Why do we put candles on top of birthday cakes? Because it's too hard to put them on the bottom.",
  "What do you call a cheap circumcision? A rip-off.",
  "Why did the scarecrow get a promotion? He was outstanding in his field.",
  "What do you call a pig that knows karate? A pork chop.",
  "Why did the ghost go to the bar? For the boos.",
  "What do you call a shoe that's a jerk? A heel.",
  "Why don't mountains catch colds? They wear snowcaps.",
  "What do you call a sleeping dinosaur? A dino-snore.",
  "Why did the math problem go to court? It had an unknown solution.",
  "What do you call a clever dinosaur? A thesaurus.",
  "Why did the astronaut break up with the planet? She needed more space.",
  "What do you call a can of soup that lies? Souperstitious.",
  "Why did the cloud date the storm? He was thunderstruck.",
  "What do you call a magic dog? A labracadabrador.",
  "Why did the baker go to therapy? He kneaded it.",
  "What do you call a pile of kittens? A meowntain.",
  "Why did the lamp get good grades? It was very bright.",
  "What do you call a tiny lie? A little fib.",
  "Why did the music note go to jail? It was in treble.",
  "What do you call a parade of rabbits hopping backward? A receding hare-line.",
  "Why did the cat go to school? It wanted to be a cool cat.",
  "What do you call an honest politician? A myth.",
  "Why did the teddy bear skip dessert? He was already stuffed.",
  "What do you call a dog who's also a doctor? A dog-tor.",
  "Why did the cheese stand alone? Because it was too grate.",
  "What do you call a train loaded with bubblegum? A chew-chew train.",
  "Why did the skeleton laugh at everything? It had a funny bone.",
  "What do you call a crocodile that's a detective? An investi-gator.",
  "Why did the pumpkin go to the doctor? It felt hollow inside.",
  "What do you call a sad cuppa tea? Despresso.",
  "Why did the vampire read the newspaper? He heard it had good circulation.",
  "What do you call a sleeping expert? A dream analyst.",
  "Why did the ocean and river break up? The ocean was too deep.",
  "What do you call a group of crows? Attempted murder.",
  "Why did the invisible man turn down the job? He couldn't see himself doing it.",
  "What do you call cheese that belongs to someone else? Their-chester.",
  "Why did the stadium flood? Because the home team was soaked.",
  "What do you call a cow that twitches? Beef jerky.",
  "Why did the book go to the hospital? It hurt its spine.",
  "What do you call a flying skunk? A stink bomb.",
  "Why did the cookie cry? Because its mother was a wafer so long.",
  "What do you call an angry pea? Grum-pea.",
  "Why did the duck go to rehab? It was hooked on quack.",
  "What do you call a famous fish? A starfish.",
  "Why did the light bulb fail the test? It was not very bright.",
  "What do you call a criminal who pulls pranks? A con artist.",
  "Why did the chef get kicked out of the kitchen? He was caught whisk-ing.",
  "What do you call a lazy robot? A rust-bot.",
  "Why did the number 5 dump the number 6? It was looking for a 10.",
  "What do you call a very excited sheep? Wool-y enthused.",
  "Why did the gym teacher get in trouble? He was caught doing chin-ups on the sly.",
  "What do you call a dog who can't bark? A hush puppy.",
  "Why did the scientist go to the party? To drop some mad science.",
  "What do you call an overworked baker? A toast case.",
  "Why did the tomato lose the race? It couldn't ketchup.",
  "What do you call a sleeping cowboy? A restless ranger.",
  "Why did the elevator break up with the stairs? He took her for granted.",
  "What do you call a very small mother? A minimum.",
  "Why did the actor fall through the stage? He was in the first cast.",
  "What do you call a rabbit with fleas? Bugs Bunny.",
  "Why did the volcano love the earthquake? It was shaken by its eruptions.",
  "What do you call a knight who is good at math? Sir Cumference.",
  "Why did the cabbage win the race? Because lettuce not lose.",
  "What do you call an ant that fights crime? A vigilant-e.",
  "Why did the watermelon go to the dentist? It had a seedy smile.",
  "What do you call a cheese that's all yours? My-mozzarella.",
  "Why did the frog go to work even when sick? He was feeling a little hoarse.",
  "What do you call a sleeping grizzly? Bear-y tired.",
  "Why did the weather get grounded? Because it was under a cloud.",
  "What do you call a pencil that's always wrong? An erasable mistake.",
  "Why did the owl always get invited to parties? Because it was a hoot.",
  "What do you call a clock that's been to space? An astro-naut.",
  "Why did the smartphone go to school? To improve its apps-titude.",
  "What do you call a helpful lemon? Lemon-aid.",
  "Why did the computer get tired? It had too many windows open.",
  "What do you call a pirate who skips school? Captain Hooky.",
  "Why did the salad win the award? It was the best-dressed.",
  "What do you call a deer with no eyes? No eye deer.",
  "Why did the traffic light turn red? Because it saw people crossing.",
  "What do you call a tuna that plays piano? A tune-a fish.",
  "Why did the dinosaur cross the road? Because chickens weren't around yet.",
  "What do you call a sad onion? Tear-ific.",
  "Why did the mailbox go on a diet? It was getting a lot of junk mail.",
  "What do you call a dinosaur that's a great salesperson? A dino-sore persuader.",
  "Why did the bee get married? It found its honey.",
  "What do you call a smart phone? An Einstein-phone.",
  "Why did the window fail school? It was always pane-ful.",
  "What do you call a detective fish? Sherlock Foams.",
  "Why did the grape go out with the raisin? The raisin was all dried up.",
  "What do you call a horse that lives next door? A neigh-bor.",
  "Why did the police officer become a teacher? He wanted to lay down the law.",
  "What do you call a sleepy dinosaur? A bronto-snore-us.",
  "Why did the cloud date the lightning bolt? It was struck by its energy.",
  "What do you call a happy cowboy? A jolly rancher.",
  "Why did the clam keep his money hidden? He was very shell-fish.",
  "What do you call a fake dragon? A fraud-gon.",
  "Why did the calendar break up with the clock? It felt like its days were numbered.",
  "What do you call a hen who counts her chicks? A mathema-ticken.",
  "Why did the math student become a pilot? He always flew through his calculations.",
  "What do you call a fish with two legs? A difish.",
  "Why did the nurse always carry a red marker? To draw blood.",
  "What do you call a monkey that loves chips? A chipanzee.",
  "Why did the lemon fail chemistry? It couldn't concentrate.",
  "What do you call a lazy lion? A lie-on.",
  "Why did the deer get a job at the bakery? It was good at making doe.",
  "What do you call a bee from America? A USB.",
  "Why did the squirrel swim across the river? To get to the other side.",
  "What do you call a slow marathon runner? A marathon walker.",
  "Why did the dog sit in the shade? Because it didn't want to be a hot dog.",
  "What do you call a bee who can't make up its mind? A maybee.",
  "Why did the orange lose the race? It ran out of juice.",
  "What do you call a cat who loves bowling? An alley cat.",
  "Why did the toaster start a fight? It was just being pushy.",
  "What do you call a cold hot dog? A chilly dog.",
  "Why did the vegetable become a detective? It liked digging into the roots.",
  "What do you call a sad avocado? Guaca-moody.",
  "Why did the bread lose the argument? It was on a roll.",
  "What do you call a super cold dog? A pupsicle.",
  "Why was the pencil so popular? It had a great point.",
  "What do you call a sick eagle? Ill-eagle.",
  "Why did the robot go to school? To improve its hardware.",
  "What do you call a lazy turtle? Slow-poke.",
  "Why did the sandwich get a ticket? It was caught between two buns.",
  "What do you call a crab who's always working? Hard-shell.",
  "Why did the onion win the debate? Its arguments were tearable.",
  "What do you call a haunted chicken? A poultry-geist.",
  "Why did the flower go to the hospital? It was petal to the metal.",
  "What do you call a lion who eats the zookeeper? The boss.",
  "Why did the fireman wear red suspenders? To keep his pants up.",
  "What do you call a hen who counts eggs? A mathema-chicken.",
  "Why did the astronaut break up with the moon? She needed more space.",
  "What do you call a fish that's a doctor? A sturgeon general.",
  "Why did the kid eat his homework? Because the teacher told him it was a piece of cake.",
  "What do you call a polite dinosaur? A please-iosaur.",
  "Why did the painter's work look sad? He could only draw a frown.",
  "What do you call a surprised bear? Incredi-bear.",
  "Why did the sock refuse to fight? It didn't want to get in-knit situations.",
  "What do you call a rabbit in the shower? A hare-conditioner.",
  "Why did the spider go on the internet? To make a website.",
  "What do you call a well-dressed ant? Elegant.",
  "Why did the broom get promoted? It swept the competition.",
  "What do you call a blind deer? No eye deer.",
  "Why did the alien go to school? To improve its space-ship.",
  "What do you call a funny mountain? Hill-arious.",
  "Why did the ice cream truck break down? It got a rocky road.",
  "What do you call a panda eating a banana? A panda-monium.",
  "Why did the dog sit in front of the fireplace? To become a hot dog.",
  "What do you call a duck that's also a dentist? Bill the dentist.",
  "Why did the boat go to school? To get a higher degree.",
  "What do you call a worm who works in tech? A software bug.",
  "Why did the newspaper get promoted? It had a great cover story.",
  "What do you call a ghost's true love? His ghoul-friend.",
  "Why did the football coach go to the bank? To get his quarterback.",
  "What do you call a cat who wins at cards? Purr-fect poker player.",
  "Why did the teddy bear never feel hungry? Because he was always stuffed.",
  "What do you call a man who shaves 20 times a day? A barber.",
  "Why did the teacher wear sunglasses to class? Because her students were so bright.",
  "What do you call a fish that's afraid of everything? A scaredy cat-fish.",
  "Why did the bee get married? He found his honey.",
  "What do you call an adventurous cheese? Brie-venturous.",
  "Why did the ocean go to the dentist? To get its wave cleaned.",
  "What do you call a fake philosopher? A phony-osopher.",
  "Why did the shoe go to the bank? To get its sole back.",
  "What do you call a haunted pasta? A spook-ghetti.",
  "Why did the giraffe get bad grades? His thoughts were above everyone else.",
  "What do you call a penguin wearing headphones? Anything—he can't hear you.",
  "Why did the banana go to the doctor? It wasn't peeling well.",
  "What do you call a cow with a sense of humor? Dairy funny.",
  "Why did the book fail school? It had too many stories to tell.",
  "What do you call a snowman temper tantrum? A meltdown.",
  "Why did the music teacher get locked out? He left his keys in.",
  "What do you call a pig who cooks? A swine chef.",
  "Why did the chemistry teacher get in trouble? He was caught mixing things up.",
  "What do you call a fish who builds things? Bob the builder.",
  "Why did the man bring a ladder to the bar? The drinks were on the house.",
  "What do you call a rooster that wakes you up every morning? An alarm cluck.",
  "Why did the egg go to school? To get egg-ducated.",
  "What do you call a shark that delivers toys? Santa Jaws.",
  "Why did the bicycle keep falling over? It was two-tired.",
  "What do you call an interesting ant? Fasci-nant.",
  "Why did the library go out of business? Its stories dried up.",
  "What do you call a cat that gets what it wants? Purrsuasive.",
  "Why did the pencil fail school? It was a dull student.",
  "What do you call a rabbit raised on the internet? A hacker.",
  "Why did the dog go to the doctor? He was a little husky.",
  "What do you call a cow who tells jokes? A dairy comedian.",
  "Why did the tree fail the test? It fell in too many branches.",
  "What do you call a sleepy swimmer? A drowsy stroker.",
  "Why did the lighthouse get fired? It couldn't keep things on the straight and narrow.",
  "What do you call a sad bowl of cereal? Moan-flakes.",
  "Why did the ocean wave to the shore? Because the shore waved first.",
  "What do you call a bee that's confused? A daze-y bee.",
  "Why did the blanket go to school? To get its degree in covering.",
  "What do you call a mischievous egg? A practical yolker.",
  "Why did the painting become famous? It was a stroke of genius.",
  "What do you call an arctic monkey? Cold steel.",
  "Why did the dumbbell go to therapy? It had too many weights.",
  "What do you call a wolf who loses track of time? A disoriented lupine.",
  "Why did the elephant fail its exam? It forgot everything.",
  "What do you call a dinosaur wearing glasses? A do-you-think-he-saw-us.",
  "Why did the rubber duck go to the doctor? It felt flat.",
  "What do you call a gorilla wearing earphones? Anything you like, he can't hear you.",
  "Why did the student bring a ladder to class? Because she heard the assignment was on a high level.",
  "What do you call a potato wearing a disguise? An under-cover spud.",
  "Why did the cat sit on the computer? To keep an eye on the mouse.",
  "What do you call a funny boat? A yacht of laughs.",
  "Why did the comedian fail to tell jokes at the airport? The security wouldn't let him through with punchlines.",
  "What do you call a sleepy puppy? A snooze hound.",
  "Why did the fridge win the award? It stayed cool under pressure.",
  "What do you call a really tiny person? Mini-me.",
  "Why did the fish get kicked out of school? It was always making waves.",
  "What do you call a polite insect? A Civil-Ant.",
  "Why did the astronaut quit his job? He needed more space.",
  "What do you call a smart fly? A house genius.",
  "Why did the tortoise beat the hare? Because slow and steady wins the race.",
  "What do you call a dog who makes music? A hound of music.",
  "Why did the math professor get angry? His students kept going off on a tangent.",
  "What do you call a snowman's money? Cold hard cash.",
  "Why did the couch break up with the television? It didn't want to be sat on anymore.",
  "What do you call a happy cowboy? A jolly wrangler.",
  "Why did the horse eat the money? Because it was fed up with having no cents.",
  "What do you call a crab who plays baseball? A pinch hitter.",
  "Why did the lizard go to school? To become a rep-tile.",
  "What do you call an old snowman? Water.",
  "Why did the goat stop eating jokes? They were too cheesy.",
  "What do you call a witch on the beach? A sandwitch.",
  "Why did the computer study art? It wanted to learn how to download.",
  "What do you call a hen who can play piano? A keyboard cluck.",
  "Why did the peanut go to the police? Someone was assaulting him.",
  "What do you call a ghost who works at a restaurant? A waiter-ghoul.",
  "Why did the firefly get detention? He was too bright for class.",
  "What do you call an octopus who works at a construction site? An octo-builder.",
  "Why did the kite go to school? To get off the ground.",
  "What do you call a cat who doesn't like strangers? A catty person.",
  "Why did the duck get a promotion? It was always up with the quackdown.",
  "What do you call a group of rabbits walking backward? A receding hare-line.",
  "Why did the mop get an award? It really cleaned up.",
  "What do you call a comedian's belt? A waist of punchlines.",
  "Why did the train stop playing music? Because it lost its track.",
  "What do you call a frozen igloo? Cold comfort.",
  "Why did the cheese get grounded? Its parents thought it was too mature.",
  "What do you call a sleeping dog? A nap-san.",
  "Why did the potato go to space? To become a moon-spud.",
  "What do you call a rooster who wakes up early? An alarming bird.",
  "Why did the sweater win the argument? It had more pull.",
  "What do you call a deer with no eyes and no legs? Still no eye deer.",
  "Why did the river apply for a job? It wanted to go with the flow.",
  "What do you call a famous horse? A neigh-borhood celebrity.",
  "Why did the cloud look so sad? It was under a lot of pressure.",
  "What do you call a rabbit who tells good jokes? A stand-up hare.",
  "Why did the hammer hit the nail on the head? It nailed it.",
  "What do you call a dishonest bakery? A fake and bake shop.",
  "Why did the kangaroo stop drinking coffee? It was too jumpy.",
  "What do you call a magical snowflake? Frosty the snowman's cousin.",
  "Why did the sock feel lonely? Because its partner was lost.",
  "What do you call a cat who sings opera? A meow-soprano.",
  "Why did the bike stand on its own? It was two-tired of falling over.",
  "What do you call a jellyfish that lives in a house? A domestic jellyfish.",
  "Why did the egg cross the road? Because it cracked under pressure.",
  "What do you call an alligator wearing a vest? An investi-gator.",
  "Why did the owl always get invited to parties? It was a real hoot.",
  "What do you call a penguin in the tropics? Sweaty.",
  "Why did the phone break up with the charger? It was tired of being charged up.",
  "What do you call a genius dog? A Bark-enstein.",
  "Why did the donut go to therapy? It felt empty inside.",
  "What do you call a lazy rooster? A sleeping bird.",
  "Why did the lamp get in trouble? It was always keeping things lit.",
  "What do you call a spider that's also a computer scientist? A web developer.",
  "Why did the snowman smile? Because it saw the snowblower.",
  "What do you call a fish who's good at guitar? A bass player.",
  "Why did the duck get promoted? It always put its bill forward.",
  "What do you call a brave ant? Valiant.",
  "Why did the coffee win an award? It was the best in the blend.",
  "What do you call a sad dog? A paw-thetic pooch.",
  "Why did the gum go to school? To stick to the lesson.",
  "What do you call a camel with no water? Dehydrated.",
  "Why did the grape date the raisin? It liked dried humor.",
  "What do you call a shark with two tails? Very confused.",
  "Why did the toilet run for president? It flushed out the competition.",
  "What do you call an amusing ghost? A funny phantom.",
  "Why did the nurse fail her test? She couldn't stomach the questions.",
  "What do you call a yak who tells jokes? A yak-omedian.",
  "Why did the blueberry go to the doctor? It was feeling berry bad.",
  "What do you call a mean rabbit? Hare-brained.",
  "Why did the sun go to school? To get its degree in solar energy.",
  "What do you call a dinosaur that's always cold? A brrrr-aciosaurus.",
  "Why did the lamp quit? It was burned out.",
  "What do you call a tiny pirate? Little pieces of eight.",
  "Why did the lettuce win the debate? It had a head start.",
  "What do you call a cow that laughs? A laughing stock.",
  "Why did the toothbrush go to school? To brush up on its skills.",
  "What do you call an insecure goat? Billy the insecure.",
  "Why did the mouse break up with the keyboard? It couldn't find the right keys.",
  "What do you call a cat who can type? A paw-grammer.",
  "Why did the umbrella get in trouble? It was too shady.",
  "What do you call a dinosaur that never gives up? A try-ceratops.",
  "Why did the polar bear refuse the job? It was too cool for school.",
  "What do you call a ghost that likes to party? A boo-gie monster.",
  "Why did the eagle get a job at the bank? Because it could spot change from a mile away.",
  "What do you call a bear that's always late? A pro-crastin-ate.",
  "Why did the clock get a speeding ticket? It was running too fast.",
  "What do you call a snowman who also races? Frosty the speed demon.",
  "Why did the apple go to school? To become a smart-apple.",
  "What do you call a frog that loves selfies? A snap-adillo.",
  "Why did the doughnut become an actor? It had a great hole-lywood look.",
  "What do you call a turtle who's good at martial arts? A ninja-toise.",
  "Why did the book fall asleep? It had too many chapters.",
  "What do you call a cow who loves art? A moo-seum exhibit.",
  "Why did the map go to the doctor? It had lost its direction.",
  "What do you call a fly with no wings? A walk.",
  "Why did the tomato turn down the job offer? It ketchup-ed everything already.",
  "What do you call a snowflake with a short temper? A flake-out.",
  "Why did the dog chase his tail? He was trying to make ends meet.",
  "What do you call a dancing chicken? A fowl performer.",
  "Why did the submarine go to school? It was tired of being low-pressure.",
  "What do you call an easily amused spider? A gigg-ant.",
  "Why did the pillow go to the doctor? It was stuffed up.",
  "What do you call a silly ant? An insane-sect.",
  "Why did the bird go to the gym? To work on its tweet muscles.",
  "What do you call a polite ghost? A please-antom.",
  "Why did the rug become a comedian? It had great floor humor.",
  "What do you call a shoe wearing a hat? A cap-soled.",
  "Why did the coffee become a detective? Because it grounded everyone.",
  "What do you call a moose who makes music? A moose-ician.",
  "Why did the penguin go to college? To get a degree in ice science.",
  "What do you call a cool deer? Hip-hop-a-deer.",
  "Why did the sock go to the gym? To work on its sole.",
  "What do you call a whale who likes to throw parties? A party-whale.",
  "Why did the skeleton go to the doctor? He was bone-tired.",
  "What do you call a very cold comedian? An icy stand-up.",
  "Why did the carrot go to school? To get ahead in life.",
  "What do you call a napping chef? A sauté-snoozer.",
  "Why did the key refuse to work? It was off-key.",
  "What do you call a very small cup of coffee? E-spresso.",
  "Why did the cloud become a rapper? It had the best flow.",
  "What do you call a frog who loves candy? A sweet-ribit.",
  "Why did the tomato go to the gym? To get its body in ketchup shape.",
  "What do you call a famous penguin? An A-list bird.",
  "Why did the shark go to school? To improve its bite-racy.",
  "What do you call a dog who works in IT? A tech-terrier.",
  "Why did the elephant apply for a job? It had a great memory.",
  "What do you call a sleepy kangaroo? A yawn-garoo.",
  "Why did the painting go to the museum? It wanted to hang out.",
  "What do you call a well-known cow? A celebrity calf.",
  "Why did the lollipop go to school? To learn how to suck-ceed.",
  "What do you call a monkey in glasses? A spec-tacular primate.",
  "Why did the potato go to the library? It wanted to read about starch.",
  "What do you call an artistic shrimp? A prawn Picasso.",
  "Why did the towel join the gym? It wanted to get buff.",
  "What do you call a sad rabbit? A melancholy hare.",
  "Why did the map blush? Because it saw the globe without any clothes on.",
  "What do you call a dog who's a locksmith? A key hound.",
  "Why did the bird fail school? Because it couldn't stop tweeting.",
  "What do you call a cat who eats lemons? A sour-puss.",
  "Why did the sock become a comedian? It had great sole humor.",
  "What do you call a sleeping crocodile? Snappy napper.",
  "Why did the lamp go on a date? It wanted to light someone's world.",
  "What do you call a confused bee? A may-bee.",
  "Why did the fish go to university? To improve its school-ing.",
  "What do you call a cow who never stops complaining? A beef-er.",
  "Why did the parrot go to school? To learn some new words.",
  "What do you call a very tall dog? A great Dane.",
  "Why did the newspaper feel depressed? Its headlines were down.",
  "What do you call a bat who tells jokes? A crack-up creature.",
  "Why did the ladder get invited to the party? It raised the bar.",
  "What do you call a famous duck? A celebrity quack.",
  "Why did the teddy bear skip lunch? She was already stuffed.",
  "What do you call a lazy T-Rex? A do-nothing dinosaur.",
  "Why did the broom apply for a job? It swept through the interview.",
  "What do you call a musical bear? A Grizzly Adams-ment.",
  "Why did the moon start a band? It liked to rock-et.",
  "What do you call a very patient cow? A slow-moo-ver.",
  "Why did the rock go to school? It wanted to become a rolling stone.",
  "What do you call a wise owl? A hoot-ellectual.",
  "Why did the cactus go to the party? It wanted to stick around.",
  "What do you call a royal fish? King of the sea bass.",
  "Why did the grape go to church? It had too many sins to wine about.",
  "What do you call a tiger wearing a Christmas hat? A roar-dolph.",
  "Why did the snowboard become famous? It had the best downhill career.",
  "What do you call a polar bear who can't swim? An ice-olated bear.",
  "Why did the coffee refuse to work overtime? It didn't want to be overroasted.",
  "What do you call a bear who's great at yoga? A flex-ible grizzly.",
  "Why did the computer go to sleep? It had too many open tabs.",
  "What do you call a duck who fixes cars? An auto-quacker.",
  "Why did the monkey sit on the clock? It wanted to be on time.",
  "What do you call a frightened diver? Chicken of the sea.",
  "Why did the hot dog stand alone? Because it relished being independent.",
  "What do you call a fake noodle at a party? An impasta-r.",
  "Why did the phone go on a diet? It had too many apps.",
  "What do you call an ant who fails all their classes? Antsy-cial.",
  "Why did the dentist become a comedian? He had a great drill for humor.",
  "What do you call a very surprised shark? Jaw-dropping.",
  "Why did the taco go to school? To get a little salsa-tion.",
  "What do you call a bunny who likes to play poker? A rabbit that bluffs.",
  "Why did the puppy sit in front of the fire? To become a hot dog.",
  "What do you call a pig that likes to party? A swine-time entertainer.",
  "Why did the waterfall get hired? It had great flow.",
  "What do you call a polite cat? A purrfectly mannered feline.",
  "Why did the mushroom get invited to every party? Because he's a fun-gi.",
  "What do you call a lazy leopard? A cheetah without effort.",
  "Why did the apple turn red? Because it saw the salad dressing.",
  "What do you call a snowman on a trampoline? A snow bouncer.",
  "Why did the ice cube go to school? To cool down its temper.",
  "What do you call a spider who's great at art? A web designer.",
  "Why did the parrot wear a suit? For a formal squawk.",
  "What do you call a lazy ghost? A pro-crast-i-boo.",
  "Why did the clam refuse to share? It was shellfish.",
  "What do you call a whale who tells jokes? A stand-up whale.",
  "Why did the candle win the race? Because it burned the competition.",
  "What do you call a dog who tells time? A paw-nctual hound.",
  "Why did the mirror fail school? It couldn't reflect on its work.",
  "What do you call a seagull who hangs out at Starbucks? A Javagull.",
  "Why did the cloud fail the test? It couldn't retain the information.",
  "What do you call a cow who's always calm? A moo-ditative animal.",
  "Why did the scissors get in trouble? They were cutting class.",
  "What do you call a bat who loves to sleep? Dracu-la-zy.",
  "Why did the hat go to school? To cap off its education.",
  "What do you call a shark who's great at poker? A card-il-rac.",
  "Why did the rubber band break up? It stretched too far.",
  "What do you call a frog with a jet pack? A leap of faith.",
  "Why did the astronaut fail his exam? He was spaced out.",
  "What do you call a nervous clock? A tick-anxious.",
  "Why did the wolf quit his job? He was howling for a change.",
  "What do you call a snake who builds things? A boa constructor.",
  "Why did the rabbit go to school? To study hare-ology.",
  "What do you call a very polite pirate? Sir-rowdee.",
  "Why did the bear join the swim team? It was a natural at the bear-stroke.",
  "What do you call a goat on a mountain? Sir Climbs-a-lot.",
  "Why did the wallet start crying? It was out of cash.",
  "What do you call a surprised mountain? A shock-peak.",
  "Why did the soda become famous? It had a great pop.",
  "What do you call a spider who's also a cowboy? Billy the Widdle.",
  "Why did the lemon join the band? Because it had great zest.",
  "What do you call a bear who can fly? Winnie the Flew.",
  "Why did the shoe refuse to argue? It had nothing to stand on.",
  "What do you call a very creative horse? A neigh-rtist.",
  "Why did the bread get a promotion? Because it rose to the occasion.",
  "What do you call a snowman with a great tan? Water.",
  "Why did the dog bring a pencil to the park? To draw some attention.",
  "What do you call a snowflake that's always right? Flake-tual.",
  "Why did the computer break up with the printer? There was no connection.",
  "What do you call a very calm firefighter? A chill-blaze.",
  "Why did the sheep apply for a job? It was looking to woool something up.",
  "What do you call a polite tornado? A manners whirlwind.",
  "Why did the bunny go to the bank? To open a hop account.",
  "What do you call a jellyfish in a tuxedo? Formal goo.",
  "Why did the lion refuse to play cards? Because he was afraid of cheetahs.",
  "What do you call a happy kangaroo? A joyful bounder.",
  "Why did the sock go to college? To become a foot doctor.",
  "What do you call a fish who's always late? Tardy tuna.",
  "Why did the snail ride on the turtle's back? To speed things up.",
  "What do you call a bear who's also a DJ? DJ Grizzly.",
  "Why did the cup go to the party? It wanted to socialize.",
  "What do you call a rabbit who's also an athlete? A hopper champion.",
  "Why did the piano go to school? To get its keys in order.",
  "What do you call a rapping duck? MC Quackers.",
  "Why did the cactus never feel lonely? It had thorny friends.",
  "What do you call a cow who plays tennis? A moo-ve-ment player.",
  "Why did the leaf fall from the tree? It felt like going with the fall.",
  "What do you call a laughing tree? A tim-birr-r tree.",
  "Why did the pepper go to the party? It was feeling jalapeño business.",
  "What do you call an artistic whale? A mural-leviathan.",
  "Why did the star go to school? To shine in academia.",
  "What do you call a fancy fish? Dashing bass.",
  "Why did the panda go on a diet? It was too bear-y chunky.",
  "What do you call a cool polar bear? An ice model.",
  "Why did the sock go to school? To get its master's degree in sole.",
  "What do you call a group of ants? An antsemble.",
  "Why did the goose join the military? For some real goose-stepping.",
  "What do you call a lazy penguin? A slow waddle.",
  "Why did the hat make everyone laugh? It had a great cap-sense of humor.",
  "What do you call a rooster who talks back? A sass-erel.",
  "Why did the deer apply for a bank loan? It was in debt to the forest.",
  "What do you call a cat who loves yoga? A purrfectly stretched feline.",
  "Why did the cow wear earmuffs? It heard too much moo-sic.",
  "What do you call a nervous spider? A jitter-web.",
  "Why did the clock refuse to sleep? It was always wound up.",
  "What do you call a crab who's also a musician? A rock-lobster.",
  "Why did the umbrella break up with the rain? It kept getting soaked.",
  "What do you call a sheep who tells jokes? A comedian ewe.",
  "Why did the fox go to school? To outfox the other students.",
  "What do you call a cow who's also a librarian? A moo-vie collector.",
  "Why did the mountain apply for a job? It had peak performance.",
  "What do you call a bat who's always sleeping? A cave-napper.",
  "Why did the banana wear sunscreen? It didn't want to peel.",
  "What do you call a fish who's afraid of water? A land lover.",
  "Why did the pea become a doctor? It had great patient peas.",
  "What do you call an excited dinosaur? A dino-more.",
  "Why did the wolf join a choir? It had a howling voice.",
  "What do you call a happy pig? A jolly hog.",
  "Why did the rabbit hate cold weather? It couldn't stand hare-frost.",
  "What do you call a frozen lake? Ice cold storage.",
  "Why did the caterpillar become famous? It was on a roll.",
  "What do you call a clever fish? A smartacuda.",
  "Why did the moth go to school? It was attracted to knowledge.",
  "What do you call a dog who's always working? A labor-ador.",
  "Why did the penguin get a raise? It was an ice employee.",
  "What do you call a chicken who loves computers? A tech-hen.",
  "Why did the dragon go to school? It wanted to learn how to breathe fire correctly.",
  "What do you call a well-behaved bird? A goody-tweet.",
  "Why did the cookie get promoted? It was on a roll.",
  "What do you call a cat who never stops purring? An en-purr-gizer.",
  "Why did the whale go to the singing lesson? To improve its whale of a voice.",
];

export default {
  data: new SlashCommandBuilder()
    .setName('joke')
    .setDescription('Get a random joke to brighten your day!'),
  category: 'Fun',

  async execute(interaction) {
    await InteractionHelper.safeDefer(interaction);
    const joke = JOKES[Math.floor(Math.random() * JOKES.length)];

    await InteractionHelper.safeEditReply(interaction, {
      embeds: [
        createEmbed({
          title: '😂 Random Joke',
          description: joke,
          color: 'joke',
          footer: { text: `Joke #${JOKES.indexOf(joke) + 1} of ${JOKES.length}` },
        }),
      ],
    });
  },
};
