import { SlashCommandBuilder } from 'discord.js';
import { createEmbed } from '../../utils/embeds.js';
import { InteractionHelper } from '../../utils/interactionHelper.js';

const QUOTES = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
  { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas Edison" },
  { text: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss" },
  { text: "If life were predictable it would cease to be life and be without flavor.", author: "Eleanor Roosevelt" },
  { text: "If you look at what you have in life, you'll always have more.", author: "Oprah Winfrey" },
  { text: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", author: "James Cameron" },
  { text: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Maya Angelou" },
  { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Money and success don't change people; they merely amplify what is already there.", author: "Will Smith" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Not how long, but how well you have lived is the main thing.", author: "Seneca" },
  { text: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt" },
  { text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "In this life we cannot do great things. We can only do small things with great love.", author: "Mother Teresa" },
  { text: "It's not whether you get knocked down; it's whether you get up.", author: "Vince Lombardi" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "To handle yourself, use your head; to handle others, use your heart.", author: "Eleanor Roosevelt" },
  { text: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown" },
  { text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks" },
  { text: "I alone cannot change the world, but I can cast a stone across the water to create many ripples.", author: "Mother Teresa" },
  { text: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn" },
  { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
  { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
  { text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { text: "Have enough courage to trust love one more time and always one more time.", author: "Maya Angelou" },
  { text: "We must believe that we are gifted for something and that this thing must be attained.", author: "Marie Curie" },
  { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.", author: "Helen Keller" },
  { text: "It is only with the heart that one can see rightly; what is essential is invisible to the eye.", author: "Antoine de Saint-Exupéry" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou" },
  { text: "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.", author: "Maya Angelou" },
  { text: "Not everything that is faced can be changed, but nothing can be changed until it is faced.", author: "James Baldwin" },
  { text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop" },
  { text: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank" },
  { text: "When I was 5 years old, my mother always told me that happiness was the key to life.", author: "John Lennon" },
  { text: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
  { text: "How many people are trapped in their everyday habits; part numb, part frightened, part indifferent?", author: "Mignon McLaughlin" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "We do not remember days, we remember moments.", author: "Cesare Pavese" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "When you change the way you look at things, the things you look at change.", author: "Wayne Dyer" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "An unexamined life is not worth living.", author: "Socrates" },
  { text: "Spread love everywhere you go.", author: "Mother Teresa" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
  { text: "Eighty percent of success is showing up.", author: "Woody Allen" },
  { text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso" },
  { text: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus" },
  { text: "I've missed more than 9,000 shots in my career. I've lost almost 300 games. Twenty-six times I've been trusted to take the game winning shot and missed.", author: "Michael Jordan" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { text: "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "People often say that motivation doesn't last. Well, neither does bathing — that's why we recommend it daily.", author: "Zig Ziglar" },
  { text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin" },
  { text: "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", author: "Vincent van Gogh" },
  { text: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle" },
  { text: "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", author: "Jesus Christ" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
  { text: "Life is not measured by the number of breaths you take but by the moments that take your breath away.", author: "Maya Angelou" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.", author: "Leonardo da Vinci" },
  { text: "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", author: "Jamie Paolinetti" },
  { text: "You take your life in your own hands, and what happens? A terrible thing: no one to blame.", author: "Erica Jong" },
  { text: "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.", author: "Bob Dylan" },
  { text: "I didn't fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin" },
  { text: "In order to succeed, your desire for success should be greater than your fear of failure.", author: "Bill Cosby" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb" },
  { text: "There are no traffic jams along the extra mile.", author: "Roger Staubach" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "You become what you believe.", author: "Oprah Winfrey" },
  { text: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
  { text: "A truly rich man is one whose children run into his arms when his hands are empty.", author: "Unknown" },
  { text: "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.", author: "Ann Landers" },
  { text: "If you want your children to turn out well, spend twice as much time with them, and half as much money.", author: "Abigail Van Buren" },
  { text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray" },
  { text: "The battles that count aren't the ones for gold medals. The struggles within yourself—the invisible battles inside all of us—that's where it's at.", author: "Jesse Owens" },
  { text: "Education costs money. But then so does ignorance.", author: "Sir Claus Moser" },
  { text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", author: "Oprah Winfrey" },
  { text: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama" },
  { text: "You can't connect the dots looking forward; you can only connect them looking backwards.", author: "Steve Jobs" },
  { text: "I believe that everything happens for a reason. People change so that you can learn to let go.", author: "Marilyn Monroe" },
  { text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker" },
  { text: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", author: "John Milton" },
  { text: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "If you're offered a seat on a rocket ship, don't ask what seat! Just get on.", author: "Sheryl Sandberg" },
  { text: "I always did something I was a little not ready to do. I think that's how you grow.", author: "Marissa Mayer" },
  { text: "You can't fall if you don't climb. But there's no joy in living your whole life on the ground.", author: "Unknown" },
  { text: "We need to accept that we won't always make the right decisions.", author: "Arianna Huffington" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "When you take risks you learn that there will be times when you succeed and there will be times when you fail, and both are equally important.", author: "Ellen DeGeneres" },
  { text: "Winning is not everything, but wanting to win is.", author: "Vince Lombardi" },
  { text: "You are never really playing an opponent. You are playing yourself, your own highest standards, and when you reach your limits, that is real joy.", author: "Arthur Ashe" },
  { text: "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.", author: "Dale Carnegie" },
  { text: "It is not the mountain we conquer, but ourselves.", author: "Sir Edmund Hillary" },
  { text: "As long as you keep going, you'll keep getting better. And as you get better, you gain more confidence.", author: "Tamara Taylor" },
  { text: "Hard times never last, but hard people do.", author: "Robert H. Schuller" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "A champion is defined not by their wins but by how they can recover when they fall.", author: "Serena Williams" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "Just when the caterpillar thought the world was ending, he turned into a butterfly.", author: "Proverb" },
  { text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain" },
  { text: "An entrepreneur is someone who jumps off a cliff and builds a plane on the way down.", author: "Reid Hoffman" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { text: "The starting point of all achievement is desire.", author: "Napoleon Hill" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { text: "All progress takes place outside the comfort zone.", author: "Michael John Bobak" },
  { text: "Don't wish it were easier; wish you were better.", author: "Jim Rohn" },
  { text: "I'm not a product of my circumstances. I'm a product of my decisions.", author: "Stephen Covey" },
  { text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author: "Mark Twain" },
  { text: "The most valuable thing you can make is a mistake — you can't learn anything from being perfect.", author: "Adam Osborne" },
  { text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward.", author: "Rocky Balboa" },
  { text: "Life is what we make it, always has been, always will be.", author: "Grandma Moses" },
  { text: "The gist of happiness is simplicity.", author: "Unknown" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "Life is 10% what happens to me and 90% of how I react to it.", author: "Charles Swindoll" },
  { text: "The most common form of despair is not being who you are.", author: "Søren Kierkegaard" },
  { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama XIV" },
  { text: "A ship in harbor is safe, but that's not what ships are for.", author: "John A. Shedd" },
  { text: "Go as far as you can see; when you get there, you'll be able to see farther.", author: "J. P. Morgan" },
  { text: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller Jr." },
  { text: "First, have a definite, clear practical ideal; a goal, an objective.", author: "Aristotle" },
  { text: "We aim above the mark to hit the mark.", author: "Ralph Waldo Emerson" },
  { text: "The great secret of success is to go through life as a man who never gets used up.", author: "Albert Schweitzer" },
  { text: "Problems are not stop signs, they are guidelines.", author: "Robert H. Schuller" },
  { text: "One way to keep momentum going is to have constantly greater goals.", author: "Michael Korda" },
  { text: "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.", author: "Wayne Dyer" },
  { text: "What seems to us as bitter trials are often blessings in disguise.", author: "Oscar Wilde" },
  { text: "The meaning of life is to find your gift. The purpose of life is to give it away.", author: "Pablo Picasso" },
  { text: "Learn from the mistakes of others. You can't live long enough to make them all yourself.", author: "Eleanor Roosevelt" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", author: "Bill Keane" },
  { text: "My mission in life is not merely to survive, but to thrive.", author: "Maya Angelou" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "The purpose of life is a life of purpose.", author: "Robert Byrne" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Defeat is not bitter unless you swallow it.", author: "Joe Clark" },
  { text: "Optimism is the faith that leads to achievement.", author: "Helen Keller" },
  { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { text: "Courage doesn't always roar. Sometimes courage is the little voice at the end of the day that says I'll try again tomorrow.", author: "Mary Anne Radmacher" },
  { text: "You were born with wings, why prefer to crawl through life?", author: "Rumi" },
  { text: "Your present circumstances don't determine where you can go; they merely determine where you start.", author: "Nido Qubein" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { text: "Choose a job you love and you will never have to work a day in your life.", author: "Confucius" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "Be kind whenever possible. It is always possible.", author: "Dalai Lama" },
  { text: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link" },
  { text: "Whether you think you can or think you can't, you're right.", author: "Henry Ford" },
  { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
  { text: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller" },
  { text: "In my experience, there is only one motivation, and that is desire.", author: "Jane Smiley" },
  { text: "It takes courage to grow up and become who you really are.", author: "E.E. Cummings" },
  { text: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
  { text: "The secret of joy in work is contained in one word — excellence.", author: "Pearl Buck" },
  { text: "Character is higher than intellect.", author: "Ralph Waldo Emerson" },
  { text: "Excellence is not a destination; it is a continuous journey that never ends.", author: "Brian Tracy" },
  { text: "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.", author: "Theodore N. Vail" },
  { text: "We become what we think about most of the time, and that's the strangest secret.", author: "Earl Nightingale" },
  { text: "The big secret in life is that there is no big secret. Whatever your goal, you can get there if you're willing to work.", author: "Oprah Winfrey" },
  { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
  { text: "Arise, awake, and stop not until the goal is achieved.", author: "Swami Vivekananda" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Success is getting what you want; happiness is wanting what you get.", author: "W.P. Kinsella" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Thomas Jefferson" },
  { text: "Keep your face to the sunshine and you cannot see a shadow.", author: "Helen Keller" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The only thing worse than being blind is having sight but no vision.", author: "Helen Keller" },
  { text: "Where there is no vision, the people perish.", author: "Proverbs 29:18" },
  { text: "Our greatest fear should not be of failure, but of succeeding at things in life that don't really matter.", author: "Francis Chan" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "As we look ahead into the next century, leaders will be those who empower others.", author: "Bill Gates" },
  { text: "Those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing.", author: "Martha Stewart" },
  { text: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau" },
  { text: "The real man smiles in trouble, gathers strength from distress, and grows brave by reflection.", author: "Thomas Paine" },
  { text: "To know what you know and what you do not know, that is true knowledge.", author: "Confucius" },
  { text: "The secret to living well and longer is: eat half, walk double, laugh triple, and love without measure.", author: "Tibetan Proverb" },
  { text: "Life is not about finding yourself. Life is about creating yourself.", author: "Lolly Daskal" },
  { text: "The mind is not a vessel to be filled but a fire to be kindled.", author: "Plutarch" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
  { text: "The only source of knowledge is experience.", author: "Albert Einstein" },
  { text: "The more that you read, the more things you will know.", author: "Dr. Seuss" },
  { text: "Intelligence plus character—that is the goal of true education.", author: "Martin Luther King Jr." },
  { text: "Upon the subject of education, not presuming to dictate any plan or system respecting it, I can only say that I view it as the most important subject which we as a people can be engaged in.", author: "Abraham Lincoln" },
  { text: "The task of the modern educator is not to cut down jungles, but to irrigate deserts.", author: "C.S. Lewis" },
  { text: "Learning is not attained by chance; it must be sought for with ardor and diligence.", author: "Abigail Adams" },
  { text: "The aim of education is the knowledge, not of facts, but of values.", author: "William S. Burroughs" },
  { text: "Children must be taught how to think, not what to think.", author: "Margaret Mead" },
  { text: "Education is simply the soul of a society as it passes from one generation to another.", author: "G.K. Chesterton" },
  { text: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein" },
  { text: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
  { text: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison" },
  { text: "Knowledge is power. Information is liberating. Education is the premise of progress.", author: "Kofi Annan" },
  { text: "Real education should educate us out of self into something far finer — into a selflessness.", author: "Vita Sackville-West" },
  { text: "The purpose of education is to replace an empty mind with an open one.", author: "Malcolm Forbes" },
  { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln" },
  { text: "Nothing great was ever achieved without enthusiasm.", author: "Ralph Waldo Emerson" },
  { text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney" },
  { text: "Kind words can be short and easy to speak, but their echoes are truly endless.", author: "Mother Teresa" },
  { text: "We must become the change we want to see.", author: "Mahatma Gandhi" },
  { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi" },
  { text: "An eye for an eye only ends up making the whole world blind.", author: "Mahatma Gandhi" },
  { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
  { text: "If you want peace, stop fighting. If you want peace of mind, stop fighting with your thoughts.", author: "Peter McWilliams" },
  { text: "Peace begins with a smile.", author: "Mother Teresa" },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "A man is but the product of his thoughts. What he thinks, he becomes.", author: "Mahatma Gandhi" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Freedom is not worth having if it does not include the freedom to make mistakes.", author: "Mahatma Gandhi" },
  { text: "The greatness of a nation can be judged by the way its animals are treated.", author: "Mahatma Gandhi" },
  { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
  { text: "To give real service you must add something which cannot be bought or measured with money, and that is sincerity and integrity.", author: "Donald A. Adams" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "Logic will get you from A to Z; imagination will get you everywhere.", author: "Albert Einstein" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "Science without religion is lame, religion without science is blind.", author: "Albert Einstein" },
  { text: "Try to become not a man of success, but try rather to become a man of value.", author: "Albert Einstein" },
  { text: "Great spirits have always encountered violent opposition from mediocre minds.", author: "Albert Einstein" },
  { text: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "Insanity is doing the same thing over and over again and expecting different results.", author: "Albert Einstein" },
  { text: "Anyone who has never made a mistake has never tried anything new.", author: "Albert Einstein" },
  { text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
  { text: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author: "Albert Einstein" },
  { text: "Only two things are infinite, the universe and human stupidity, and I'm not sure about the former.", author: "Albert Einstein" },
  { text: "Without courage, wisdom bears no fruit.", author: "Baltasar Gracián" },
  { text: "Wisdom is the reward you get for a lifetime of listening when you'd have preferred to talk.", author: "Doug Larson" },
  { text: "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.", author: "Confucius" },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { text: "The man who does not read has no advantage over the man who cannot read.", author: "Mark Twain" },
  { text: "Classic — a book which people praise and don't read.", author: "Mark Twain" },
  { text: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain" },
  { text: "Age is an issue of mind over matter. If you don't mind, it doesn't matter.", author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain" },
  { text: "Never put off till tomorrow what may be done day after tomorrow just as well.", author: "Mark Twain" },
  { text: "Keep away from people who try to belittle your ambitions. Small people always do that.", author: "Mark Twain" },
  { text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
  { text: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { text: "Wherever you go, go with all your heart.", author: "Confucius" },
  { text: "He who learns but does not think, is lost. He who thinks but does not learn is in great danger.", author: "Confucius" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "When you see a good person, think of becoming like her/him. When you see someone not so good, reflect on your own weak points.", author: "Confucius" },
  { text: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
  { text: "Never give up, for that is just the place and time that the tide will turn.", author: "Harriet Beecher Stowe" },
  { text: "You cannot swim for new horizons until you have courage to lose sight of the shore.", author: "William Faulkner" },
  { text: "I know not all that may be coming, but be it what it will, I'll go to it laughing.", author: "Herman Melville" },
  { text: "It is our choices that show what we truly are, far more than our abilities.", author: "J.K. Rowling" },
  { text: "What we think, we become.", author: "Buddha" },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
  { text: "To understand everything is to forgive everything.", author: "Buddha" },
  { text: "You yourself, as much as anybody in the entire universe, deserve your love and affection.", author: "Buddha" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
  { text: "Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened.", author: "Buddha" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "Believe nothing, no matter where you read it, or who said it, unless it agrees with your own reason.", author: "Buddha" },
  { text: "The secret of health for both mind and body is not to mourn for the past, nor to worry about the future.", author: "Buddha" },
  { text: "The soul that sees beauty may sometimes walk alone.", author: "Johann Wolfgang von Goethe" },
  { text: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
  { text: "Whatever you do, or dream you can, begin it. Boldness has genius and power and magic in it.", author: "Johann Wolfgang von Goethe" },
  { text: "Thinking is easy, acting is difficult, and to put one's thoughts into action is the most difficult thing in the world.", author: "Johann Wolfgang von Goethe" },
  { text: "Dream no small dreams for they have no power to move the hearts of men.", author: "Johann Wolfgang von Goethe" },
  { text: "Man errs as long as he strives.", author: "Johann Wolfgang von Goethe" },
  { text: "None but ourselves can free our minds.", author: "Bob Marley" },
  { text: "Open your eyes, look within. Are you satisfied with the life you're living?", author: "Bob Marley" },
  { text: "Love the life you live. Live the life you love.", author: "Bob Marley" },
  { text: "One good thing about music, when it hits you, you feel no pain.", author: "Bob Marley" },
  { text: "Every man gotta right to decide his own destiny.", author: "Bob Marley" },
  { text: "Don't gain the world and lose your soul; wisdom is better than silver or gold.", author: "Bob Marley" },
  { text: "You never know how strong you are, until being strong is your only choice.", author: "Bob Marley" },
  { text: "The truth is, unless you let go, unless you forgive yourself, unless you forgive the situation, unless you realize that the situation is over, you cannot move forward.", author: "Steve Maraboli" },
  { text: "To think is easy. To act is hard. But the hardest thing in the world is to act in accordance with your thinking.", author: "Johann Wolfgang von Goethe" },
  { text: "The privilege of a lifetime is being who you are.", author: "Joseph Campbell" },
  { text: "Life is not a problem to be solved, but a reality to be experienced.", author: "Søren Kierkegaard" },
  { text: "The older I get, the greater power I seem to have to help the world; I am like a snowball — the further I am rolled the more I gain.", author: "Susan B. Anthony" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "Ask not what your country can do for you — ask what you can do for your country.", author: "John F. Kennedy" },
  { text: "Efforts and courage are not enough without purpose and direction.", author: "John F. Kennedy" },
  { text: "The time to repair the roof is when the sun is shining.", author: "John F. Kennedy" },
  { text: "Change is the law of life. And those who look only to the past or present are certain to miss the future.", author: "John F. Kennedy" },
  { text: "Forgive your enemies, but never forget their names.", author: "John F. Kennedy" },
  { text: "As we express our gratitude, we must never forget that the highest appreciation is not to utter words, but to live by them.", author: "John F. Kennedy" },
  { text: "Too often we enjoy the comfort of opinion without the discomfort of thought.", author: "John F. Kennedy" },
  { text: "Conformity is the jailer of freedom and the enemy of growth.", author: "John F. Kennedy" },
  { text: "Victory has a thousand fathers, but defeat is an orphan.", author: "John F. Kennedy" },
  { text: "Let us not seek the Republican answer or the Democratic answer, but the right answer.", author: "John F. Kennedy" },
  { text: "Those who make peaceful revolution impossible will make violent revolution inevitable.", author: "John F. Kennedy" },
  { text: "Mankind must put an end to war before war puts an end to mankind.", author: "John F. Kennedy" },
  { text: "Leadership and learning are indispensable to each other.", author: "John F. Kennedy" },
  { text: "If not us, who? If not now, when?", author: "John F. Kennedy" },
  { text: "We choose to go to the Moon in this decade and do the other things, not because they are easy, but because they are hard.", author: "John F. Kennedy" },
  { text: "The greatest legacy one can pass on to one's children and grandchildren is not money or other material things accumulated in one's life, but rather a legacy of character and faith.", author: "Billy Graham" },
  { text: "Courage is contagious. When a brave man takes a stand, the spines of others are often stiffened.", author: "Billy Graham" },
  { text: "God never takes away something from your life without replacing it with something better.", author: "Billy Graham" },
  { text: "It is the Holy Spirit's job to convict, God's job to judge and my job to love.", author: "Billy Graham" },
  { text: "Nothing can bring a real sense of security into the home except true love.", author: "Billy Graham" },
  { text: "Give me five minutes with a person's checkbook, and I will tell you where their heart is.", author: "Billy Graham" },
  { text: "Being a Christian is more than just an instantaneous conversion — it is a daily process whereby you grow to be more and more like Christ.", author: "Billy Graham" },
  { text: "We are the children of our age, but children who can never know their mother.", author: "Wisława Szymborska" },
  { text: "Every day may not be good, but there is something good in every day.", author: "Alice Morse Earle" },
  { text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
  { text: "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.", author: "Mother Teresa" },
  { text: "Be present in all things and thankful for all things.", author: "Maya Angelou" },
  { text: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", author: "Henry Ford" },
  { text: "I am thankful for all of those who said NO to me. It's because of them I'm doing it myself.", author: "Albert Einstein" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { text: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
  { text: "If you do what you've always done, you'll get what you've always gotten.", author: "Tony Robbins" },
  { text: "Dreaming, after all, is a form of planning.", author: "Gloria Steinem" },
  { text: "I used to want the words 'She tried' on my tombstone. Now I want 'She did it.'", author: "Katherine Dunham" },
  { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
  { text: "I am not afraid of tomorrow, for I have seen yesterday and I love today.", author: "William Allen White" },
  { text: "What would you attempt to do if you knew you could not fail?", author: "Robert H. Schuller" },
  { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
  { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
  { text: "Believe and act as if it were impossible to fail.", author: "Charles Kettering" },
  { text: "Remember no one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "With self-discipline most anything is possible.", author: "Theodore Roosevelt" },
  { text: "Blessed are those who can give without remembering and take without forgetting.", author: "Elizabeth Bibesco" },
  { text: "Do what you feel in your heart to be right, for you'll be criticized anyway.", author: "Eleanor Roosevelt" },
  { text: "A really great talent finds its happiness in execution.", author: "Johann Wolfgang von Goethe" },
  { text: "The most wasted of all days is one without laughter.", author: "E.E. Cummings" },
  { text: "To be content with what we possess is the greatest and most secure of all riches.", author: "Marcus Tullius Cicero" },
  { text: "You can do anything, but not everything.", author: "David Allen" },
  { text: "I've come to believe that all my past failure and frustration were actually laying the foundation for the understandings that have created the new level of living I now enjoy.", author: "Tony Robbins" },
  { text: "For every reason it's not possible, there are hundreds of people who have faced the same circumstances and succeeded.", author: "Jack Canfield" },
  { text: "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don't quit.", author: "Conrad Hilton" },
  { text: "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.", author: "Seneca" },
  { text: "I dwell in possibility.", author: "Emily Dickinson" },
  { text: "Hope is the thing with feathers that perches in the soul.", author: "Emily Dickinson" },
  { text: "Not knowing when the dawn will come, I open every door.", author: "Emily Dickinson" },
  { text: "Forever is composed of nows.", author: "Emily Dickinson" },
  { text: "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.", author: "John Quincy Adams" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Steve Jobs" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs" },
  { text: "The people who are crazy enough to think they can change the world, are the ones who do.", author: "Steve Jobs" },
  { text: "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.", author: "Steve Jobs" },
  { text: "Sometimes life hits you in the head with a brick. Don't lose faith.", author: "Steve Jobs" },
  { text: "I would rather die of passion than of boredom.", author: "Émile Zola" },
  { text: "There is nothing so useless as doing efficiently that which should not be done at all.", author: "Peter F. Drucker" },
  { text: "Effective leadership is not about making speeches or being liked; leadership is defined by results not attributes.", author: "Peter F. Drucker" },
  { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
  { text: "We always overestimate the change that will occur in the next two years and underestimate the change that will occur in the next ten.", author: "Bill Gates" },
  { text: "It's fine to celebrate success but it is more important to heed the lessons of failure.", author: "Bill Gates" },
  { text: "I choose a lazy person to do a hard job. Because a lazy person will find an easy way to do it.", author: "Bill Gates" },
  { text: "If you think you are too small to make a difference, try sleeping with a mosquito.", author: "Dalai Lama" },
  { text: "Happiness is not ready made. It comes from your actions.", author: "Dalai Lama" },
  { text: "If you can, help others; if you cannot do that, at least do not harm them.", author: "Dalai Lama" },
  { text: "Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.", author: "Dalai Lama" },
  { text: "My religion is very simple. My religion is kindness.", author: "Dalai Lama" },
  { text: "This is my simple religion. No need for temples. No need for complicated philosophy. Your own mind, your own heart is the temple.", author: "Dalai Lama" },
  { text: "Old friends pass away, new friends appear. It is just like the days. An old day passes, a new day arrives. The important thing is to make it meaningful: a meaningful friend — or a meaningful day.", author: "Dalai Lama" },
  { text: "When we feel love and kindness toward others, it not only makes others feel loved and cared for, but it helps us also to develop inner happiness and peace.", author: "Dalai Lama" },
  { text: "We must recognize that the suffering of one person or one nation is the suffering of humanity.", author: "Dalai Lama" },
  { text: "The measure of who we are is what we do with what we have.", author: "Vince Lombardi" },
  { text: "Leaders aren't born, they are made. And they are made just like anything else, through hard work.", author: "Vince Lombardi" },
  { text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.", author: "Vince Lombardi" },
  { text: "Once you learn to quit, it becomes a habit.", author: "Vince Lombardi" },
  { text: "Confidence is contagious. So is lack of confidence.", author: "Vince Lombardi" },
  { text: "The will to win is not nearly so important as the will to prepare to win.", author: "Vince Lombardi" },
  { text: "Individual commitment to a group effort — that is what makes a team work, a company work, a society work, a civilization work.", author: "Vince Lombardi" },
  { text: "The quality of a person's life is in direct proportion to their commitment to excellence, regardless of their chosen field of endeavor.", author: "Vince Lombardi" },
  { text: "If winning isn't everything, why do they keep score?", author: "Vince Lombardi" },
  { text: "Fatigue makes cowards of us all.", author: "Vince Lombardi" },
  { text: "To be kind is more important than to be right.", author: "Unknown" },
  { text: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston S. Churchill" },
  { text: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill" },
  { text: "The price of greatness is responsibility.", author: "Winston Churchill" },
  { text: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.", author: "Winston Churchill" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "It's not enough that we do our best; sometimes we must do what's required.", author: "Winston Churchill" },
  { text: "Success is not final; failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Continuous effort — not strength or intelligence — is the key to unlocking our potential.", author: "Winston Churchill" },
  { text: "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.", author: "Winston Churchill" },
  { text: "History is written by the victors.", author: "Winston Churchill" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Men occasionally stumble over the truth, but most of them pick themselves up and hurry off as if nothing ever happened.", author: "Winston Churchill" },
  { text: "The truth is incontrovertible. Malice may attack it, ignorance may deride it, but in the end, there it is.", author: "Winston Churchill" },
  { text: "There is no limit to what a man can do or where he can go if he doesn't mind who gets the credit.", author: "Ronald Reagan" },
  { text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { text: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", author: "Maya Angelou" },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
  { text: "If you're always trying to be normal, you will never know how amazing you can be.", author: "Maya Angelou" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { text: "I've learned that making a living is not the same thing as making a life.", author: "Maya Angelou" },
  { text: "A bird doesn't sing because it has an answer, it sings because it has a song.", author: "Maya Angelou" },
  { text: "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.", author: "Maya Angelou" },
  { text: "You are the sum total of everything you've ever seen, heard, eaten, smelled, been told, forgot — it's all there.", author: "Maya Angelou" },
  { text: "Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently.", author: "Maya Angelou" },
  { text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { text: "Words mean more than what is set down on paper. It takes the human voice to infuse them with shades of deeper meaning.", author: "Maya Angelou" },
  { text: "When you know better you do better.", author: "Maya Angelou" },
  { text: "My great hope is to laugh as much as I cry; to get my work done and try to love somebody and have the courage to accept the love in return.", author: "Maya Angelou" },
  { text: "We are more alike, my friends, than we are unalike.", author: "Maya Angelou" },
  { text: "A wise man makes his own decisions, an ignorant man follows public opinion.", author: "Chinese Proverb" },
  { text: "An inch of time is an inch of gold, but you can't buy that inch of time with an inch of gold.", author: "Chinese Proverb" },
  { text: "Be not afraid of growing slowly; be afraid only of standing still.", author: "Chinese Proverb" },
  { text: "Better a diamond with a flaw than a pebble without.", author: "Confucius" },
  { text: "Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime.", author: "Chinese Proverb" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "He who knows others is wise; he who knows himself is enlightened.", author: "Lao Tzu" },
  { text: "Act without expectation.", author: "Lao Tzu" },
  { text: "Life is a series of natural and spontaneous changes. Don't resist them — that only creates sorrow.", author: "Lao Tzu" },
  { text: "The key to growth is the introduction of higher dimensions of consciousness into our awareness.", author: "Lao Tzu" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "A leader is best when people barely know he exists. When his work is done, his aim fulfilled, they will say: we did it ourselves.", author: "Lao Tzu" },
  { text: "Simplicity, patience, compassion. These three are your greatest treasures.", author: "Lao Tzu" },
  { text: "If you realize that all things change, there is nothing you will try to hold on to.", author: "Lao Tzu" },
  { text: "To the mind that is still, the whole universe surrenders.", author: "Lao Tzu" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
  { text: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Lao Tzu" },
  { text: "Be careful about reading health books. You may die of a misprint.", author: "Mark Twain" },
  { text: "Under certain circumstances, profanity provides a relief denied even to prayer.", author: "Mark Twain" },
  { text: "Let us live so that when we come to die even the undertaker will be sorry.", author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Good judgment is the result of experience and experience the result of bad judgment.", author: "Mark Twain" },
  { text: "The more I learn about people, the more I like my dog.", author: "Mark Twain" },
  { text: "Education: the path from cocky ignorance to miserable uncertainty.", author: "Mark Twain" },
  { text: "If you don't read the newspaper, you're uninformed. If you read the newspaper, you're mis-informed.", author: "Mark Twain" },
  { text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain" },
  { text: "Keep away from people who try to belittle your ambitions.", author: "Mark Twain" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
  { text: "Man is least himself when he talks in his own person. Give him a mask, and he will tell you the truth.", author: "Oscar Wilde" },
  { text: "I am so clever that sometimes I don't understand a single word of what I am saying.", author: "Oscar Wilde" },
  { text: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde" },
  { text: "The truth is rarely pure and never simple.", author: "Oscar Wilde" },
  { text: "A good friend will always stab you in the front.", author: "Oscar Wilde" },
  { text: "The only way to get rid of a temptation is to yield to it.", author: "Oscar Wilde" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { text: "No good deed goes unpunished.", author: "Oscar Wilde" },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde" },
  { text: "The books that the world calls immoral are the books that show the world its own shame.", author: "Oscar Wilde" },
  { text: "What is a cynic? A man who knows the price of everything and the value of nothing.", author: "Oscar Wilde" },
  { text: "It is what you read when you don't have to that determines what you will be when you can't help it.", author: "Oscar Wilde" },
  { text: "All women become like their mothers. That is their tragedy. No man does, and that is his.", author: "Oscar Wilde" },
  { text: "The world is a book, and those who do not travel read only one page.", author: "Saint Augustine" },
  { text: "Our heart is restless until it finds its rest in Thee.", author: "Saint Augustine" },
  { text: "Thou hast made us for thyself, O Lord, and our heart is restless until it finds its rest in thee.", author: "Saint Augustine" },
  { text: "Faith is to believe what you do not see; the reward of this faith is to see what you believe.", author: "Saint Augustine" },
  { text: "God has promised forgiveness to your repentance, but He has not promised tomorrow to your procrastination.", author: "Saint Augustine" },
  { text: "Our soul is restless until it rests in You.", author: "Saint Augustine" },
  { text: "Love, and do what you will.", author: "Saint Augustine" },
  { text: "To fall in love with God is the greatest romance; to seek him the greatest adventure; to find him, the greatest human achievement.", author: "Saint Augustine" },
  { text: "Miracles are not contrary to nature, but only contrary to what we know about nature.", author: "Saint Augustine" },
  { text: "You have made us for yourself, and our heart is restless until it rests in you.", author: "Saint Augustine" },
  { text: "He who created us without our help will not save us without our consent.", author: "Saint Augustine" },
  { text: "Pray as though everything depended on God. Work as though everything depended on you.", author: "Saint Augustine" },
  { text: "Patience is the companion of wisdom.", author: "Saint Augustine" },
  { text: "The measure of love is to love without measure.", author: "Saint Augustine" },
  { text: "Our heart is restless, until it repose in Thee.", author: "Saint Augustine" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
  { text: "Success is not to be pursued; it is to be attracted by the person you become.", author: "Jim Rohn" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Success is doing ordinary things extraordinarily well.", author: "Jim Rohn" },
  { text: "Let others lead small lives, but not you.", author: "Jim Rohn" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "We must all suffer one of two things: the pain of discipline or the pain of regret or disappointment.", author: "Jim Rohn" },
  { text: "The challenge of leadership is to be strong, but not rude; be kind, but not weak; be bold, but not bully; be thoughtful, but not lazy.", author: "Jim Rohn" },
  { text: "You are the average of the five people you spend the most time with.", author: "Jim Rohn" },
  { text: "Don't wish it was easier; wish you were better. Don't wish for less problems; wish for more skills.", author: "Jim Rohn" },
  { text: "If you are not willing to risk the unusual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { text: "You must constantly ask yourself these questions: Who am I around? What are they doing to me?", author: "Jim Rohn" },
  { text: "Work harder on yourself than you do on your job.", author: "Jim Rohn" },
  { text: "Character isn't something you were born with and can't change, like your fingerprints. It's something you weren't born with and must take responsibility for forming.", author: "Jim Rohn" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "The secret is to work less as individuals and more as a team.", author: "Knute Rockne" },
  { text: "A team is only as strong as its weakest link.", author: "Unknown" },
  { text: "Talent wins games, but teamwork and intelligence wins championships.", author: "Michael Jordan" },
  { text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Michael Jordan" },
  { text: "To be successful you have to be selfish, or else you never achieve. And once you get to your highest level, then you have to be unselfish. Stay reachable. Stay in touch. Don't isolate.", author: "Michael Jordan" },
  { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
  { text: "Limits, like fear, is often an illusion.", author: "Michael Jordan" },
  { text: "Always turn a negative situation into a positive situation.", author: "Michael Jordan" },
  { text: "My attitude is that if you push me towards something that you think is a weakness, then I will turn that perceived weakness into a strength.", author: "Michael Jordan" },
  { text: "Heart is what separates the good from the great.", author: "Michael Jordan" },
  { text: "One day you will look back and see that all along you were blooming.", author: "Morgan Harper Nichols" },
  { text: "You don't get to choose how you're going to die, or when. But you can decide how you're going to live now.", author: "Joan Baez" },
  { text: "A man who has never gone to school may steal from a freight car; but if he has a university education, he may steal the whole railroad.", author: "Theodore Roosevelt" },
  { text: "The only man who never makes a mistake is the man who never does anything.", author: "Theodore Roosevelt" },
  { text: "With ordinary talent and extraordinary perseverance, all things are attainable.", author: "Thomas Fowell Buxton" },
  { text: "Permanence, perseverance and persistence in spite of all obstacles, discouragements, and impossibilities: It is this, that in all things distinguishes the strong soul from the weak.", author: "Thomas Carlyle" },
  { text: "The secret of success in life is for a man to be ready for his opportunity when it comes.", author: "Benjamin Disraeli" },
  { text: "Prepare and prevent, don't repair and repent.", author: "Unknown" },
  { text: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", author: "Helen Keller" },
  { text: "Be kind, for everyone you meet is fighting a harder battle.", author: "Plato" },
  { text: "The first step in the acquisition of wisdom is silence, the second listening, the third memory, the fourth practice, the fifth teaching others.", author: "Solomon Ibn Gabirol" },
  { text: "Patience, persistence and perspiration make an unbeatable combination for success.", author: "Napoleon Hill" },
  { text: "You might well remember that nothing can bring you success but yourself.", author: "Napoleon Hill" },
  { text: "Whatever your mind can conceive and can believe, it can achieve.", author: "Napoleon Hill" },
  { text: "Set your target and keep trying until you reach it.", author: "Napoleon Hill" },
  { text: "The starting point of all achievement is DESIRE. Keep this constantly in mind. Weak desire brings weak results, just as a small fire makes a small amount of heat.", author: "Napoleon Hill" },
  { text: "Strength and growth come only through continuous effort and struggle.", author: "Napoleon Hill" },
  { text: "Think twice before you speak, because your words and influence will plant the seed of either success or failure in the mind of another.", author: "Napoleon Hill" },
  { text: "Effort only fully releases its reward after a person refuses to quit.", author: "Napoleon Hill" },
  { text: "Don't wait. The time will never be just right.", author: "Napoleon Hill" },
  { text: "No man is ever whipped until he quits — in his own mind.", author: "Napoleon Hill" },
  { text: "Wise men speak because they have something to say; fools because they have to say something.", author: "Plato" },
  { text: "Education is teaching our children to desire the right things.", author: "Plato" },
  { text: "At the touch of love, everyone becomes a poet.", author: "Plato" },
  { text: "Human behavior flows from three main sources: desire, emotion, and knowledge.", author: "Plato" },
  { text: "The first and greatest victory is to conquer yourself.", author: "Plato" },
  { text: "Opinion is the medium between knowledge and ignorance.", author: "Plato" },
  { text: "Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.", author: "Aristotle" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "The more you know, the more you know you don't know.", author: "Aristotle" },
  { text: "Pleasure in the job puts perfection in the work.", author: "Aristotle" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "The whole is more than the sum of its parts.", author: "Aristotle" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { text: "Happiness is the meaning and the purpose of life, the whole aim and end of human existence.", author: "Aristotle" },
  { text: "The energy of the mind is the essence of life.", author: "Aristotle" },
  { text: "To write well, express yourself like common people, but think like a wise man.", author: "Aristotle" },
  { text: "We cannot learn without pain.", author: "Aristotle" },
  { text: "No great mind has ever existed without a touch of madness.", author: "Aristotle" },
  { text: "The secret to humor is surprise.", author: "Aristotle" },
  { text: "Good is the proper end of all action.", author: "Aristotle" },
  { text: "I count him braver who overcomes his desires than him who conquers his enemies, for the hardest victory is over self.", author: "Aristotle" },
  { text: "Nature does nothing without purpose or uselessly.", author: "Aristotle" },
  { text: "Courage is the first of human qualities because it is the quality which guarantees the others.", author: "Aristotle" },
  { text: "Fear is pain arising from the anticipation of evil.", author: "Aristotle" },
];

export default {
  data: new SlashCommandBuilder()
    .setName('quote')
    .setDescription('Get an inspiring random quote!'),
  category: 'Fun',

  async execute(interaction) {
    await InteractionHelper.safeDefer(interaction);
    const quote = QUOTES[Math.floor(Math.random() * QUOTES.length)];

    await InteractionHelper.safeEditReply(interaction, {
      embeds: [
        createEmbed({
          title: '💬 Inspirational Quote',
          description: `*"${quote.text}"*\n\n— **${quote.author}**`,
          color: 'primary',
          footer: { text: `Quote ${QUOTES.indexOf(quote) + 1} of ${QUOTES.length}` },
        }),
      ],
    });
  },
};
